<?include("app/views/scripts/header.phtml");?>
<div class="bread">You are here &gt; <a href="<?=base()?>/admin"><?=submenutitle($this->submenu_selected)?></a> &gt; Ticket Clustering</div>


<h3>Ticket Clustering</h3>
<br/>
<p>
Following are groupings of similar tickets that are modified withtin last 30 days. Only groups with more than 3 tickets are displayed.
</p>
<?
foreach($this->groups as $tickets) 
{
    if(count($tickets) > 2) {
        $first = true;
        foreach($tickets as $ticket) {
            if($first) {
                $first = false;
                $desc = $ticket->desc;
                echo "<h3>[$ticket->id] $ticket->title</h3>";
                echo "<blockquote>";
                echo "<pre>$desc</pre>";
                echo "</blockquote>";
                echo "<p><a href='$ticket->url'>Open This Ticket</a></p>";
                echo "<div class='indent'>";
                echo "<h4>Similar Tickets</h4>";
            } else {
                $score = round($ticket->score);
                echo "<a target='_blank' href='$ticket->url' style='opacity: ".($score/100).";'>[$ticket->id] $score% $ticket->title ($ticket->status)</a><br/>";
            }
        }
        echo "</div><br/><br/>";
    }
}
?>
<?include("app/views/scripts/footer.phtml");?>
