<?include("app/views/scripts/header.phtml");?>
<div class="bread">You are here &gt; <a href="<?=base()?>/open">Open Ticket</a> &gt; Membership to the OSG</div>
<!--a href="https://twiki.grid.iu.edu/bin/view/VO/OSG">Requesting OSG VO Membership</a-->
<h2>Ticket Request Form</h2>
<div class="form">
<?
if($this->errors != "") {
    echo "<p class='errors'>".$this->errors."</p>";
}
?>
<?=$this->form?>
</div>
<?include("app/views/scripts/footer.phtml");?>
