<?php echo $this->render("bootheader.phtml", true);?>
<div class="container-fluid">
<?php echo $this->alerts();?>
<div class="page-header"><h2><?php echo $this->page_title?> / Preview</h2></div>

<form action="bulkresource/submit" method="post">
<p class="help-block">Please verify below content and click Submit below.</p>
<?
foreach($this->preview as $rname=>$preview) {
    echo "<h4>".$rname."</h4>";
    echo "<blockquote><b>Ticket Detail</b><pre>";
    print_r($preview);
    echo "</pre>";

    echo "<b>Metadata</b><pre>";
    print_r($this->metadata[$rname]);
    echo "</pre>";

    echo "</blockquote>";
}
?>
<div class="form-actions">
<button type="submit" name="submit_button" class="btn btn-primary btn-large" id="submit_button">Submit</button> or <a href="bulkresource?redo=true">Modify</a>
</div>

</form>

<?php echo $this->render("pagefooter.phtml", true);?>
</div><!--container-fluid-->
<?php echo $this->render("bootfooter.phtml", true);?>

