<?php echo $this->render("bootheader.phtml", true);?>
<div class="container-fluid">
<?php echo $this->alerts();?>
<div class="page-header"><h2><?php echo $this->page_title?> / Result</h2></div>

<?
if(count($this->failed) == 0) {
    echo "<p>All tickets were successfully submitted.</p>";
} else {
    echo "<h4>Failed Tickets</h4>";
    echo "<p>Following resources has failed to submit tickets</p>";
    foreach($this->failed as $rname=>$e) {
        echo "<b>".$rname."</b><br/>";
        echo "<blockquote>$e</blockquote>";
    }
}
echo "<h4>Submitted Tickets</h4>";
foreach($this->success as $rname=>$id) {
    echo "<b>".$rname."</b><br/>";
    if(config()->simulate) {
        echo "<p>Simulation Dump</p>";
        echo "<blockquote><pre>".print_r($id, true)."</pre></blockquote>";
    } else {
        echo "<a target=\"_blank\" href=\"$id\">Ticket $id</a><br/>";
    }
}
?>

<?php echo $this->render("pagefooter.phtml", true);?>
</div><!--container-fluid-->
<?php echo $this->render("bootfooter.phtml", true);?>


