<?include("app/views/scripts/header.phtml");?>
<div class="bread">Home</div>
<h3>Please select from following options</h3>
<div class="form">

    <div class="sidenote">
    Search tickets by a keyword or ticket ID ...
    <br/><br/>

<form target="_blank" method="get" action="http://www.google.com/search">
<input type="text"  name="q" maxlength="255" value="" />
<input type="submit" value="Search" />
<input type="hidden"  name="sitesearch" value="oim.grid.iu.edu/gocticket/viewer" />
</form>


    <br/><br/>
    <a href="opentickets">Show All Open Ticket</a>
    </div>

    <div>
    I'd like to open a ticket regarding ...
    <br><br>
    <p><a href="security">A Security Incident</a></p>
    <p><a href="bdii">A BDII Service Outage</a></p>
    <p><a href="resource">An Issue Affecting a Specific OSG Resource</a></p>
    <p><a href="membership">Membership to the OSG</a></p>
    <br/>
    <p><a href="other">Any Others Issue</a>
    </div>
</div>
<?include("app/views/scripts/footer.phtml");?>


