<?include("app/views/scripts/header.phtml");?>
<div class="bread">Home</div>
<h3>Please select from following options</h3>
<div class="menu">

    <div class="sidenote" style="background-color: #ccc; padding: 10px">

    Search Ticket:
    <br/>
<form action="http://www.google.com/cse" id="cse-search-box">
  <div>
    <input type="hidden" name="cx" value="016752695275174109936:9u1k_fz_bag" />
    <input type="hidden" name="ie" value="UTF-8" />
    <input type="text" name="q"/>
    <input type="submit" name="sa" value="Search" style="min-width: 100px;"/>
  </div>
</form>
<script type="text/javascript" src="http://www.google.com/coop/cse/brand?form=cse-search-box&lang=en"></script>

    <br/>
    View Ticket by ID:<br/>
    <input type="text" id="ticketid" style="width: 70px;"/>
    <input type="button" value="Open" style="min-width: 100px;" onclick="document.location='<?=fullbase()."/viewer?id="?>'+$('#ticketid').val();"/>

    <br/><br/>
    <a href="opentickets">Show All Open Ticket</a>
    </div>

    <div>
    I'd like to open a ticket regarding ...
    <br><br>
    <p><a href="security">A Security Incident</a></p>
    <p><a href="bdii">A BDII Service Outage</a></p>
    <p><a href="resource">An Issue Affecting a Specific OSG Resource</a></p>
    <p><a href="membership">Membership to the OSG</a></p>
    <br/>
    <p><a href="other">Any Others Issue</a>
    </div>
    <br/></br>
</div>
<?include("app/views/scripts/footer.phtml");?>


