<?php
function outputItem($view, $item) {
?>
    <item>
      <guid><?php echo fullbase()."/".$item["id"]."#".$item["time"]?></guid>
      <title><?php echo $item["id"]." : ".$view->escape($item["title"])?></title>
      <link><?php echo fullbase()."/".$item["id"]?></link>
      <pubDate><?php echo date("D, j M Y G:i:s", $item["time"])?> GMT</pubDate>
      <description><?php 
        $desc = $item["description"];
        $desc = str_replace("\n", "<br>\n", $desc);
        echo $view->escape($desc);
        /*
    foreach($item["descriptions"] as $desc) {
        echo $view->escape($desc);
    }
        */
        ?></description>
    </item> 
<?
}
$title = "GOC Ticket Update Feed";
?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
    <atom:link href="<?php echo fullbase()?>/rss?<?php echo $_SERVER["QUERY_STRING"]?>" rel="self" type="application/rss+xml" />
    <title><?php echo $title?></title>
    <link><?php echo fullbase()?>/list/open</link>
    <description>RSS Feed for the latest GOC ticket updates</description>
    <image>
        <title><?php echo $title?></title>
        <url><?php echo fullbase()?>/images/osglogo.40x30.png</url>
        <link><?php echo fullbase()?>/list/open</link>
    </image>
    <?php
    foreach($this->items as $item) {
        outputItem($this, $item);
    }
    ?> 
</channel>
</rss>

