<form action="<?=$this->escape($this->element->getAction())?>"
      method="<?=$this->escape($this->element->getMethod())?>">

<?=$this->render("yourinfo.phtml", true)?>

    <h3>Request Detail</h3>
    <?=$this->element->req_type?>
    <?=$this->element->req_id?>
    <br/>

    <?=$this->element->vo?>
    <br/>

    <?=$this->element->req_sponsor?>
    <?=$this->element->req_name?>
    <?=$this->element->req_email?>
    <?=$this->element->req_phone?>
    <?=$this->element->req_dn?>
    <br/>

    <?=$this->element->submit_button?>

</form>
