<?include("app/views/scripts/header.phtml");?>
<div class="bread">You are here &gt; Open Ticket </div>
<h3>Please select from following options</h3>
<div class="menu">

    <div>
    I'd like to open a ticket regarding ...
    <br><br>
    <p><a href="security">A Security Incident</a></p>
    <p><a href="bdii">A BDII Service Outage</a></p>
    <p><a href="resource">An Issue Affecting a Specific OSG Resource</a></p>
    <p><a href="membership">Membership to the OSG</a></p>
    <br/>
    <p><a href="other">Any Others Issue</a>
    </div>

    <br/></br>
    <br clear=all>
</div>

<?if(in_array(role::$goc_admin, user()->roles)) {?>
<br/>
<h3>OSG GOC staff forms</h3>
<div class="menu">
    <div>
    You are authorized to do following as well ...
    <br><br>
    <p><a href="ra">Send certificate request email</a></p>
    </div>
</div>
<?}?> 

<?include("app/views/scripts/footer.phtml");?>


