<?include("app/views/scripts/header.phtml");?>
<style>
table.menu {
margin: 0px;
padding: 0px;
}
table.menu td {
padding-right: 20px;
}
table.menu h4 {
width: 300px;
}
</style>

<div class="bread">You are here &gt; <?=submenutitle($this->submenu_selected)?></div>
<h3>Problem / Bugs / Feature Requests</h3>
<div class="bitindent">
    <p>I would like to open a ticket regarding...</p>

    <table class="menu">
    <tr>
    <?if(config()->role_prefix == "gocticket_") {?>
        <td>
        <h4>Site or VO related</h4>
        <p><a href="resource">Problem on OSG Resource</a></p>
         <p><a href="vo">Problem with VO (provided software)</a></p>
        <p><a href="membership">Becoming a Member of OSG VOs</a></p>
        </td>

        <td>
        <h4>Central Services</h4>
        <p><a href="bdii">GOC BDII (is.grid.iu.edu)</a></p>
        <p><a href="gocticket">GOC Ticket</a></p>
        <p><a href="myosg">MyOSG</a></p>
        <p><a href="oim">OIM</a></p>
        <p><a href="software">OSG Software Cache</a></p>
        <p><a href="ress">ReSS</a></p>
        <p><a href="twiki">Twiki</a></p>
        </td>

        <td>
        <h4>Others</h4>
        <p><a href="security">Security Incident</a></p>
        <p><a href="other">Others Issue</a></p>
        </td>

    <?} else {?>
        <td>
        <p><a href="resource">An Issue Affecting a Specific ITB Resource</a></p>
        <p><a href="other">Any Others Issue</a></p>
        </td>
    <?}?>

    </tr>
    </table>
</div>


<?if(user()->allows("admin")) {?>
<br/>
<h3>OSG GOC staff</h3>
<div class="bitindent">
    <p>You are authorized to submit these additional types of tickets as OSG GOC Staff...</p>
    <div>
    <p><a href="rsv">Submit RSV related trouble ticket</a></p>
    </div>
</div>
<?}?> 

<?include("app/views/scripts/footer.phtml");?>


