<?include("app/views/scripts/header.phtml");?>

<div class="bread">You are here &gt; <?=submenutitle($this->submenu_selected)?></div>
<h3>Please select from following options</h3>
<div class="menu">

    <div>
    I'd like to open a ticket regarding ...
    <br><br>
    <p><a href="security">A Security Incident</a></p>
    <p><a href="bdii">A BDII Service Outage</a></p>
    <p><a href="membership">Membership to the OSG</a></p>
    <p><a href="resource">An Issue Affecting a Specific ITB Resource</a></p>
    <p><a href="other">Any Others Issue</a>
    </div>
</div>

<?if(user()->allows("ticket_admin")) {?>
<br/>
<h3>OSG GOC staff</h3>
<div class="menu">
    <div>
    You are authorized to do following as OSG GOC Staff...
    <br><br>
    <p><a href="ra">Send certificate request email</a></p>
    <p><a href="rsv">Submit RSV related trouble ticket</a></p>
    </div>
</div>
<?}?> 

<?if(user()->allows("ticket_notify")) {?>
<br/>
<h3>OSG security staff</h3>
<div class="menu">
    <div>
    You are authorized to do following as OSG Security Staff...
    <br><br>
    <p><a href="notify">Send Notification Email/RSS</a></p>
    </div>
</div>
<?}?> 

<?include("app/views/scripts/footer.phtml");?>


