<?php echo $this->render("bootheader.phtml", true);?>
<div class="container">
<?php echo $this->alerts();?>
<div class="page-header"><h2><?php echo $this->page_title?></h2></div>
<div class="form">
<?if($this->errors != "") {
    echo "<div class='alert alert-error'>".$this->errors."</div>";
}?>
<?=$this->form?>
</div><!--form-->
<?php echo $this->render("pagefooter.phtml", true);?>
</div><!--container-fluid-->
<?php echo $this->render("bootfooter.phtml", true);?>
