<div class="container">
<footer>
    <div class="container">
    <?php echo "<p>".config()->app_name." Version ".config()->version; ?>
     | <a href="https://ticket.grid.iu.edu/goc/submit?app_issue_check=on&amp;app_issue_type=goc&amp;app_goc_url=<?=urlencode(fullurl())?>">Report Bugs</a>
     | <a href="https://github.com/opensciencegrid/operations/blob/master/docs/privacy.md">Privacy Policy</a>
    </p>

    <p> <img align="top" src="<?=base()?>/images/tag_orange.png"/> <?=config()->copyright?></p>
    </div>
</footer>
</div>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("<?=config()->urchin_account?>");
pageTracker._trackPageview();
} catch(err) {}
</script>

</body>
</html>
