<!DOCTYPE html>
<html lang="en">
  <head>
    <base href="<?php echo base()?>/">
    <!--[if IE]>
    <script type="text/javascript">
        //fix ie's broken base href handling
        function toAbsURL(s) {
         var l = location, h, p, f, i;
         if (/^\w+:/.test(s)) { return s; }
         h = l.protocol + '//' + l.host + (l.port!=''?(':' + l.port):'');
         if (s.indexOf('/') == 0) { return h + s; }
         p = l.pathname.replace(/\/[^\/]*$/, '');
         f = s.match(/\.\.\//g);
         if (f) {
           s = s.substring(f.length * 3);
           for (i = f.length; i--;) { p = p.substring(0, p.lastIndexOf('/')); }
         }
         return h + p + '/' + s;
       }
    var base = document.getElementsByTagName('base')[0];
    base.href = toAbsURL(base.href);
    </script>
    <![endif]-->

    <?
    if(isset($this->page_title)) {
        echo "<title>".$this->page_title."</title>";
    } else {
        echo "<title>".config()->app_name."</title>";
    }
    ?>
    <meta charset="utf-8">
    <meta name="verify-v1" content="na5IcAJsZVOfEkboRxuIiZ1zpZgnZiWra+nKcS7nA/o=" />
    <meta name="google-site-verification" content="DLrk3ft4s8b-S2TloLCL2LD_t6wcTjgSluf5pmiu2kA" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <link href="<?php echo fullbase()?>/rss" rel="alternate" type="application/rss+xml" title="GOC Ticket Update feed" />

    <style type="text/css">
      body {
        padding-top: 50px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }
     #search {
            width: 300px;
     }

    </style>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/bootstrap/2.3.2/css/bootstrap.min.css" rel="stylesheet"/>
    <script src="//netdna.bootstrapcdn.com/bootstrap/2.3.2/js/bootstrap.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet"/>
    <link href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.min.css" rel="stylesheet"/>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>

    <link href="css/ticket.css" rel="stylesheet">
    <script src="lib/jquery.cookie.js"></script>

    <link href="images/tag_orange.png" rel="icon" type="image/png"/>

  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>

            <a class="brand" style="padding: 6px 0px 0px 6px;" href="http://opensciencegrid.org"><img src="images/osglogo.40x30.png"></a>
            <ul class="nav">
                <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo config()->app_name?> <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                    <li><a href="https://myosg.grid.iu.edu">MyOSG</a></li>
                    <li><a href="https://oim.grid.iu.edu">OIM</a></li>
                    <li class="active"><a href="index">Ticket</a></li>
                    <li><a href="https://twiki.grid.iu.edu">TWiki</a></li>
                    <li class="divider"></li>
                    <li><a href="http://repo.grid.iu.edu">Repo</a></li>
                    <li><a href="http://is.grid.iu.edu">OSG BDII</a></li>
                    <li class="divider"></li>
                    <li><a href="http://blogs.grid.iu.edu">Blog</a></li>
                    <li><a href="http://display.grid.iu.edu">Display</a></li>
                    <li><a href="http://osggoc.blogspot.com/">News</a></li>
                    </ul>
                </li>
            </ul>
            <div class="nav-collapse">
                <ul class="nav">
                    <li id="menu_submit"><a href="submit">Submit</a></li>
                    <li id="menu_view" class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">View <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                        <li id="submenu_listopen"><a href="list/open">Open Tickets</a></li>
                        <li id="submenu_listrecentclose"><a href="list/recentclose">Recently Closed Tickets</a></li>
                        <li class="divider"></li>
                        <li id="submenu_alltickets"><a href="search?q=&sort=id">All Tickets</a></li>
                        </ul>
                    </li>                
                </ul>
                <ul class="nav pull-right">
                    <?php
                    if(!user()->isGuest()) {
                        echo "<li class=\"dropdown\">";
                        echo "<a id=\"menu_user\" href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">";
                        echo user()->getPersonName()." <span class=\"caret\"></span></a>";

                        echo "<ul class=\"dropdown-menu\">";
                        if(user()->allows("admin") || user()->allows("notify")) {
                            echo "<li class=\"nav-header\">Notification</li>";
                            if(user()->allows("admin")) {
                                echo "<li id=\"submenu_notify\"><a href=\"notify\">GOC Notification</a></li>";
                            }
                            if(user()->allows("notify")) {
                                echo "<li id=\"submenu_simplenotify\"><a href=\"simplenotify\">Security Notification</a></li>";
                            }
                            echo "<li class=\"divider\"></li>";
                        }

                        echo "<li class=\"nav-header\">Ticket Submitter</li>";
                        if(user()->allows("notify")) {
                            echo "<li id=\"submenu_securityannounceticket\"><a href=\"securityannounceticket\">Security Ticket</a></li>";
                        }
                        if(user()->allows("admin")) {
                            echo "<li id=\"submenu_bulkresource\"><a href=\"bulkresource\">Bulk Resource Tickets</a></li>";
                            echo "<li id=\"submenu_custom\"><a href=\"custom\">Custom Ticket</a></li>";
                            echo "<li id=\"submenu_ra\"><a href=\"ra\">Certificate Request</a></li>";
                        }
                        echo "<li id=\"submenu_campus\"><a href=\"campus\">CRC Request Form</a></li>";
                        echo "<li class=\"divider\"></li>";

                        if(user()->allows("admin")) {
                            echo "<li class=\"nav-header\">Administration</li>";
                            echo "<li id=\"submenu_finderror\"><a href=\"finderror\">Footprints Errors</a></li>";
                            //echo "<li id=\"submenu_group\"><a href=\"group\">Ticket Clustering</a></li>";
                            echo "<li id=\"submenu_assignment\"><a href=\"assignment\">Assignment</a></li>";
                            echo "<li class=\"divider\"></li>";
                        }

                        echo "<li><a href=\"http://".$_SERVER["SERVER_NAME"].base()."\">Logoff</a></li>";
                        echo "</ul>";
                        echo "</li>";
                    } else if(@$_SERVER['HTTPS'] == "on") {
                        if(Zend_Registry::isRegistered("unregistered_dn")) {
                            echo "<li><a href=\"https://oim.grid.iu.edu/oim/register\">Register</a></li>";
                        } else if(Zend_Registry::isRegistered("disabled_dn")) {
                            echo "<li><a href=\"http://".$_SERVER["SERVER_NAME"].base()."\">(Disabled)</a></li>";
                        } else {
                            echo "<li><a href=\"http://".$_SERVER["SERVER_NAME"].base()."\">(NoCert)</a></li>";
                        }
                    } else {
                        //probably via http
                        echo "<li><a href=\"https://".$_SERVER["SERVER_NAME"].$_SERVER["REQUEST_URI"]."\">Login</a></li>";
                    }

                    ?>
                </ul>

                <form class="navbar-search pull-right" action="viewer">
                    <input id="search" type="text" name="id" class="search-query span2" placeholder="Search Ticket" value="<?php echo @$this->query?>">
                </form>
            </div>

        </div>
      </div>
    </div>

