<div id="footer">
<p><?=config()->copyright?></p>
Report bugs at <a href="http://code.google.com/p/osggoc/issues/entry">GOC Bug Tracker</a><br/>
<p><a href="https://myosg.grid.iu.edu">MyOSG</a> | GOCTicket | <a href="https://oim.grid.iu.edu">OIM</a> | <a href="https://twiki.grid.iu.edu">TWiki</a></p>
</div>

</div>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("<?=config()->urchin_account?>");
pageTracker._trackPageview();
} catch(err) {}</script>
</body>
</html>
