</div>

<div id="footer">
<?
echo "<div style=\"float: right; text-align: right\">";

echo "<p>".config()->app_name." Version ".config()->version;
if(config()->debug) {
    exec("svn info | grep \"Revision:\" |  awk '{print $2}'", $out);
    echo " (Rev. ".$out[0].")";
}
echo "</p>";

echo "<p>Logged in as <b>";
if(user()->isGuest()) {
    echo "Guest";
} else {
    echo user()->getDN();
}
echo "</b></p>";

echo "</div>";
?>
<p>
<a href="https://myosg.grid.iu.edu/">MyOSG</a> |
<a href="https://is.grid.iu.edu/documentation.html">BDII</a> |
GOC Ticket | 
<a href="https://oim.grid.iu.edu">OIM</a> |
<a href="http://software.grid.iu.edu">OSG Software Cache</a> |
<a href="https://twiki.grid.iu.edu">TWiki</a> |
<a href="http://osggoc.blogspot.com">GOC News Blog</a> |
<a href="https://ticket.grid.iu.edu/goc/gocticket?ref=<?=urlencode(fullurl())?>">Report Bugs</a></p>
<!-- |
Other Operational Services:
<a href="http://gratia-osg-prod-reports.opensciencegrid.org/gratia-reporting/">Gratia Accounting</a>
-->
</p>
<p><img align="left" src="<?=base()?>/images/tea.png"/>&nbsp;<?=config()->copyright?></p>
</div>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("<?=config()->urchin_account?>");
pageTracker._trackPageview();
} catch(err) {}</script>
</body>
</html>
