</div>

<div id="footer">
<?

echo "<p>".config()->app_name." Version ".config()->version;
if(config()->debug) {
    exec("svn info | grep \"Revision:\" |  awk '{print $2}'", $out);
    echo " (Rev. ".$out[0].")";
}
echo " | ";
?>
<a href="https://ticket.grid.iu.edu/goc/gocticket?ref=<?=urlencode(fullurl())?>">Report Bugs</a>
<?
echo "</p>";

echo "<p>Logged in as <b>";
if(user()->isGuest()) {
    echo "Guest";
} else {
    echo user()->getDN()." (".user()->getTimeZone().")";
}
echo "</b>";

?>
</p>

<p> <img align="top" src="<?=base()?>/images/tag_orange.png"/>&nbsp;<?=config()->copyright?></p>
</div>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("<?=config()->urchin_account?>");
pageTracker._trackPageview();
} catch(err) {}</script>
</body>
</html>
