<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="verify-v1" content="na5IcAJsZVOfEkboRxuIiZ1zpZgnZiWra+nKcS7nA/o=" />
    <meta name="robots" content="noarchive">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="<?=base()?>/css/normal.css" type="text/css" media="screen"/>
    <link rel="search" type="application/opensearchdescription+xml" href="<?=base()?>/opensearch/id" title="GOC Ticket (by ID)">
    <link rel="stylesheet" href="<?=base()?>/lib/jquery/theme/ui.all.css" type="text/css" media="screen"/>
    <script type="text/javascript" src="<?=base()?>/lib/jquery/jquery.js"></script>
    <script type="text/javascript" src="<?=base()?>/lib/jquery/jquery.ui.all.js"></script>

    <link rel="stylesheet" type="text/css" href="<?=base()?>/css/jquery.autocomplete.css" />
    <script type="text/javascript" src="<?=base()?>/lib/jquery/plugins/jquery.autocomplete.min.js"></script>

    <?
    if(isset($this->page_title)) {
        echo "<title>".$this->page_title."</title>";
    } else {
        echo "<title>".config()->app_name."</title>";
    }
    ?>
</head>
<body>
<h1><?=config()->app_name?></h1>
<?
function submenutitle($id)
{
    switch($id) {
    case "open":
        return "Submit A Ticket";
    case "view":
        return "View Tickets";
    case "admin":
        return "Administration";
    }
}
?>
<div class="submenu" id="submenu_rsv">
    <span id="submenu_open"><a href="<?=base()?>/open" accesskey="1"><?=submenutitle("open")?></a></span>
    <span id="submenu_view"><a href="<?=base()?>/navigator" accesskey="2"><?=submenutitle("view")?></a></span>
<?
if(in_array(role::$goc_admin, user()->roles)) {
?>
    <span id="submenu_admin"><a href="<?=base()?>/admin" accesskey="3"><?=submenutitle("admin")?></a></span>
<?}?>
</div>
<script type="text/javascript">
    $("#submenu_<?=$this->submenu_selected?>").addClass("selected");
</script>

<div class="container">

<?include("app/views/scripts/search.phtml");?>

<?
if(config()->simulate) {
    echo "<p class=\"warning\">Simulation Mode - No email / ticket will be actually created</p>";
}

if(config()->debug) {
    echo "<p class=\"warning\">Running in Debug mode</p>";
}
