<hr/>
<footer>
<?php echo "<p>".config()->app_name." Version ".config()->version; ?>
 | <a href="https://ticket.opensciencegrid.org/goc/submit?app_issue_check=on&amp;app_issue_type=goc&amp;app_goc_url=<?=urlencode(fullurl())?>">Report Bugs</a>
 | <a href="https://github.com/opensciencegrid/operations/blob/master/docs/privacy.md">Privacy Policy</a>
</p>

<p> <img align="top" src="<?=base()?>/images/tag_orange.png"/> <?=config()->copyright?></p>
</footer>


