<div class="searchbox">
        <form action="http://www.google.com/cse" id="cse-search-box">
          <div>
            <input type="hidden" name="cx" value="016752695275174109936:9u1k_fz_bag" />

            <input type="hidden" name="ie" value="UTF-8" />
            <input type="text" name="q" size="30"/>
            <input type="submit" name="sa" value="Search" style="min-width: 75px;"/>
          </div>
        </form>
        <script type="text/javascript" src="http://www.google.com/coop/cse/brand?form=cse-search-box&lang=en"></script>
        <p></p>

        Open By Ticket ID: 
        <input type="text" id="ticketid" style="width: 75px;padding: 1px;"/>
        <input type="button" value="Open" style="min-width: 75px;" onclick="document.location='https://oim-dev.grid.iu.edu/gocticket/viewer?id='+$('#ticketid').val();"/>

</div>

