<?
$content = "";
if(config()->simulate) {
    include("app/views/scripts/header.phtml");
    $content .= "<h3>Simulation Dump</h3>";
    $content .= "<p>Running in simulation mode. The ticket was not actually created. Following is what would've been sent to FP in real mode.</p>";
    $content .= "<pre style=\"background-color: #ccc;\">";
    $content .= htmlspecialchars($this->mrid);
    $content .= "</pre>";
    echo $content;
    include("app/views/scripts/footer.phtml");
} else {
    header("location: ".fullbase()."/viewer?id=".$this->mrid);

    //store message in session, and redirect
    addMessage("<p>Thank you for submitting your ticket.</p>");
    addMessage("<p>If your issues needs action in less than <b>24 hours</b> as stated in the <a href=\"https://twiki.grid.iu.edu/bin/view/Operations/TicketExpectations\">Ticket Expectations</a>, please contact the GOC at +1-317-278-9699 or by responding to this ticket via email.</p>");

    //we now need to add exit - or header(location) won't take effect..
    exit;
}
