<?include("app/views/scripts/ticket_scripts.phtml");?>
<?php
if(!isset($form_action)) {
    $form_action = "viewer/update";
}
?>

<form id="ticket_form" class="form-horizontal" action="<?php echo $form_action?>" method="post">
    <div class="control-group">
        <input type="hidden" name="id" value="<?=$this->ticket_id?>"/>
        <?php if(isset($this->ticket_id)) {?>
            <div class="input-prepend">
                <span class="add-on"><?php echo $this->ticket_id?></span><input class="span7" type="text" name="title" value="<?=$this->title?>"/>
            </div>
        <?php } else {?>
            <input style="width: 100%;" type="text" name="title" placeholder="Ticket Title" value="<?php echo $this->title?>"/>
        <?php } ?>
    </div>

    <div class="row-fluid">
    <div class="span5">
        <legend>Contact</legend>
        <div class="control-group" style="background-color: #eee;">
            <label class="control-label" for="careof">Populate From</label>
            <div class="controls"><input type='text' id="careof" class="span12"/></div>
            <script type="text/javascript">
            $(function() {
                $("#careof").autocomplete({
                    source: persons,
                    select: function(event, ui) {
                        $("input[name=submitter_name]").val(ui.item.name);
                        $("input[name=submitter_email]").val(ui.item.email);
                        $("input[name=submitter_phone]").val(ui.item.phone);
                    }
                });
            });
            </script>
        </div>
        <div class="control-group">
            <label class="control-label" for="name">Full Name</label>
            <div class="controls"><input type='text' class="span12" name="submitter_name" value="<?php echo $this->submitter_name?>"/></div>
        </div>
        <div class="control-group">
            <label class="control-label" for="email">Email</label>
            <div class="controls"><input type='text' class="span12" name="submitter_email" value="<?php echo $this->submitter_email?>"/></div>
        </div>
        <div class="control-group">
            <label class="control-label" for="email">Phone</label>
            <div class="controls"><input type='text' class="span12" name="submitter_phone" value="<?php echo $this->submitter_phone?>"/></div>
        </div>
        <div class="control-group">
            <label class="control-label" for="cc">CC</label>
            <div class="controls">
                <div class="ccarea">
                    <?php
                    include_once("app/views/cc_editor.php");
                    cceditor($this->cc);
                    ?>
                </div>
                <a class="btn btn-mini" href="#" onclick="addcc($('.ccarea'));return false;"><i class="icon-plus"></i> Add CC</a>
            </div>
        </div>

        <legend>Details</legend>
        <?php
        $sc_id = $r_id = $vo_id = null;
        if(count($this->metadata) != 0) {
            foreach($this->metadata as $item) {
                switch($item->key) {
                case "SUPPORTING_SC_NAME": break;
                case "SUPPORTING_SC_ID": 
                    $sc_id = $item->value;
                    break;
                case "ASSOCIATED_R_NAME": break;
                case "ASSOCIATED_R_ID": 
                    $r_id = $item->value;
                    break;
                case "ASSOCIATED_RG_NAME": break;
                case "ASSOCIATED_RG_ID": break;
                case "ASSOCIATED_VO_NAME": break;
                case "ASSOCIATED_VO_ID": 
                    $vo_id = $item->value;
                    break;
                default: 
                    //just display key/value
                    echo "<div class=\"control-group\">";
                    echo "<label class=\"control-label\">$item->key</label>";
                    echo "<div class=\"controls\">";
                    echo "<input type=\"text\" disabled class=\"span12\" value=\"$item->value\" name=\"metadata[$item->key]\"/>";
                    echo "</div>";//controls
                    echo "</div>";//control-group
                }
            }
        }

        echo "<div class=\"control-group\">";
        echo "<label class=\"control-label\">Associated Resource</label>";
        echo "<div class=\"controls\">";
        echo $this->rselector($r_id);
        echo "</div>";//controls
        echo "</div>";//control-group

        echo "<div class=\"control-group\">";
        echo "<label class=\"control-label\">Support Center</label>";
        echo "<div class=\"controls\">";
        echo $this->scselector($sc_id);
        echo "</div>";//controls
        echo "</div>";//control-group

        echo "<div class=\"control-group\">";
        echo "<label class=\"control-label\">Associated VO</label>";
        echo "<div class=\"controls\">";
        echo $this->voselector($vo_id);
        echo "</div>";//controls
        echo "</div>";//control-group
        ?>

        <div class="control-group">
            <label class="control-label" for="ticket_type">Ticket Type</label>
            <div class="controls">
            <select name="ticket_type" class="span12">
            <?php
            $ttype = Footprint::GetTicketTypes();
            foreach($ttype as $type) {
                $selected = "";
                if($type == $this->ticket_type) $selected = "selected=selected";
                echo "<option value=\"$type\" $selected>$type</option>";
            }
            ?>
            </select>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="priority">Priority</label>
            <div class="controls">
            <select name="priority" class="span12">
            <?php
            $plist = Footprint::GetPriorityList();
            foreach($plist as $id=>$p) {
                $selected = "";
                if($p == $this->priority) $selected = "selected=selected";
                echo "<option value=\"$id\" value=\"$id\" $selected>$p</option>";
            }
            ?>
            </select>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="status">Status</label>
            <div class="controls">
            <select name="status" class="span12">
            <?php
            $style = status2style($this->status);
            foreach(Footprint::GetStatusList() as $status) {
                $selected = "";
                if($status == $this->status) $selected = "selected=selected";
                $style = status2style($status);
                echo "<option value=\"$status\" $selected class='ticketid $style'>$status</option>";
            }
            ?>            
            </select>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="next_action">Next Action</label>
            <div class="controls">
            <input type="text" class="span12" name="next_action" value="<?=$this->next_action?>"/>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="nad">Next Action Deadline</label>
            <div class="controls">
            <input type="text" class="span12" name="nad" value="<?=$this->nad?>"/>
            </div>
        </div>

    </div><!-- span-->

    <div class="span7">
        <?php 
        echo "<legend>Assignees";
        if(user()->allows("admin")) {
            ?> 
            <span class="pull-right" style="font-size: 11px">
            <a target="_blank" href="https://internal.grid.iu.edu/twiki/bin/view/Documentation/Ticketing/TicketAssignmentTips">Assignment Tip</a>
            </span> <?php 
        } 
        echo "</legend>";
        function showTeams($teams, $assignees, $ids, $txlinks) {
            foreach($ids as $id) {
                $team = $teams[$id];
                echo "<b class=\"teamname\">".Footprint::parse($team->team)."</b>";
                if(sizeof($team->members) > 12) {
                    echo fblist("team_$id", $team->members, $assignees, 1000, 200);
                } else {
                    echo checklist("team_$id", $team->members, $assignees, $txlinks);
                }
                echo "<br>";
            }
        }
        echo "<div class=\"row-fluid control-group\">";
        echo "<div class=\"span4\">";
        showTeams($this->teams, $this->assignees, config()->editor_teams[0], $this->txlinks);
        echo "</div>";
        echo "<div class=\"span4\">";
        showTeams($this->teams, $this->assignees, config()->editor_teams[1], $this->txlinks);
        echo "</div>";
        echo "<div class=\"span4\">";
        showTeams($this->teams, $this->assignees, config()->editor_teams[2], $this->txlinks);
        echo "</div>";
        echo "</div>";//row

        ?>
        <legend>Ticket Links</legend>
        <div class=\"control-group\">
            <style>
            input.select2-search__field {
            box-shadow: none !important;
            }
            </style>
            <select id="ticket_links" multiple="multiple" style="width: 100%;"></select>
            <script>
            function formatRepo (ticket) {
                if (ticket.loading) return ticket.text;
                var markup = '<div>' +
                '<b>' + ticket.id + '</b> ' + ticket.title+
                ' <span class="label">' + ticket.status+ '</span> ' +
                '</div>';
                return markup;
            }

            function formatRepoSelection (ticket) {
                return "<span data-ticket-id='"+ticket.id+"'><b>"+ticket.id+"</b> "+ticket.title;
            }

            $('#ticket_links').select2({
                ajax: {
                    url: "<?php echo fullbase()?>/search",
                    dataType: 'json',
                    delay: 250,
                    data: function (params) {
                      return {
                        q: params.term, 
                        json: true,
                        s: params.page*10, //start
                      };
                    },
                    processResults: function (data, page) {
                      // parse the results into the format expected by Select2.
                      // since we are using custom formatting functions we do not need to
                      // alter the remote JSON data
                      return {
                        results: data.response.docs
                      };
                    },
                    cache: true
                },
                escapeMarkup: function (markup) { return markup; }, // let our custom formatter work
                minimumInputLength: 1,
                templateResult: formatRepo, // omitted for brevity, see the source of this page
                templateSelection: formatRepoSelection // omitted for brevity, see the source of this page
            });
            </script>
        </div>
        <?php

        if(isset($this->ticket_id)) {
            echo "<br><div class=\"control-group\">";
            include("app/views/scripts/ticket_attachment.phtml");
            echo "</div>";
        } else { 
            //echo "<p class=\"muted\">Please submit your ticket before adding any attachments.</p>";
        } 
        ?>
        
    </div><!-- span-->
    </div><!-- row-->

    <legend>New Update
    <script>
    function quickdesc_change(it) {
        if($(it).val()) {
            expand_description();
            $(".description").focus();
            $.ajax({
                url: 'viewer/quickdesc?id='+escape($(it).val()),
                success: function(data) {
                    $('.description').val(data);
                }
            });
        }
    }
    </script>
    <select class="quickdesc" name="quickdesc" onchange="quickdesc_change(this);">
    <?php
    $model = new Schema();
    $descs = $model->getquickdesc();
    echo "<option value=\"\">(Template)</option>";
    foreach($descs as $name=>$desc) {
        echo "<option value=\"$name\">$name</option>";
    }
    ?>
    </select>
    </legend>
    <textarea class="description" name="description" onkeypress="checkTab(event);"><?=$this->description?></textarea>
    <div class="form-actions">
        <?php
        if(!isset($submit_label)) {
            $submit_label = "Update";
        }?>
        <div class="controls">
        <button type="submit" class="btn btn-primary"><?php echo $submit_label?></button>
        <?php
        if(isset($suppression_control)) {?>
            &nbsp;&nbsp;<input id="notify1" type="checkbox" name="notify_assignees" value="on" checked=checked"/> <label for="notify1">Notify Assignees</label>
            &nbsp;&nbsp;<input id="notify2" type="checkbox" name="notify_submitter" value="on" checked=checked"/> <label for="notify2">Notify Submitter</label>
            &nbsp;&nbsp;<input id="notify3" type="checkbox" name="notify_ccs" value="on" checked=checked"/> <label for="notify3">Notify CCs</label>
            <div id="closewindow_area" style="display: inline-block">
            &nbsp;&nbsp;<input id="closewindow" type="checkbox" name="closewindow" value="on"/> <label for="closewindow">Close Window</label>
            </div>
        <?}?>
        </div>
    </div>

</form>
