<link rel="stylesheet" type="text/css" href="<?=base()?>/lib/Upload/jquery.fileupload-ui.css" />
<script type="text/javascript" src="<?=base()?>/lib/Upload/jquery.tmpl.min.js"></script>
<script type="text/javascript" src="<?=base()?>/lib/Upload/jquery.iframe-transport.js"></script>
<script type="text/javascript" src="<?=base()?>/lib/Upload/jquery.fileupload.js"></script>
<script type="text/javascript" src="<?=base()?>/lib/Upload/jquery.fileupload-ui.js"></script>
<style>
td.attachments {
width: 420px;
}
</style>

<div id="fileupload" style="width: 100%;">
    <div class="well" style="padding: 10px;">
        <table class="files"></table>
        <label class="fileinput-button" style="position: relative; top: 6px;">
            <a class="btn btn-small"><i class="icon-plus"></i>  Add Attachments</a>
            <input style="display: none;" type="file" name="files[]" multiple>
        </label>
        <!--[if !IE]><!-->
        <div style="float: right; color: gray; position: relative; top: -22px;">Drag &amp; Drop Attachments Here</div>
        <!--<![endif]-->
    </div>
</div>
<script id="template-upload" type="text/x-jquery-tmpl">
    <tr class="template-upload{{if error}} ui-state-error{{/if}}">
        <td class="preview"></td>
        <td class="name">
            ${name}<br>
            {{if error}}
                <div class="error">Error:
                    {{if error === 'maxFileSize'}}File is too big
                    {{else error === 'minFileSize'}}File is too small
                    {{else error === 'acceptFileTypes'}}Filetype not allowed
                    {{else error === 'maxNumberOfFiles'}}Max number of files exceeded
                    {{else}}${error}
                    {{/if}}
                </div>
            {{else}}
                <div class="progress"><div></div></div>
            {{/if}}
        </td>
        <td class="size">${sizef}</td>
        <td class="cancel"><button>Cancel</button></td>
    </tr>
</script>
<script id="template-download" type="text/x-jquery-tmpl">
    <tr class="template-download{{if error}} ui-state-error{{/if}}">
        {{if error}}
            <td colspan="3" class="name">${name} ${sizef}<br>
                <div class="error">Error:
                    {{if error === 1}}File exceeds upload_max_filesize (php.ini directive)
                    {{else error === 2}}File exceeds MAX_FILE_SIZE (HTML form directive)
                    {{else error === 3}}File was only partially uploaded
                    {{else error === 4}}No File was uploaded
                    {{else error === 5}}Missing a temporary folder
                    {{else error === 6}}Failed to write file to disk
                    {{else error === 7}}File upload stopped by extension
                    {{else error === 'maxFileSize'}}File is too big
                    {{else error === 'minFileSize'}}File is too small
                    {{else error === 'acceptFileTypes'}}Filetype not allowed
                    {{else error === 'maxNumberOfFiles'}}Max number of files exceeded
                    {{else error === 'uploadedBytes'}}Uploaded bytes exceed file size
                    {{else error === 'emptyResult'}}Empty file upload result
                    {{else}}${error}
                    {{/if}}
                </div>
            </td>
        {{else}}
            <td class="preview">
                {{if thumbnail_url}}
                    <a href="${url}" target="_blank"><img src="${thumbnail_url}"></a>
                {{/if}}
            </td>
            <td class="name">
                <a href="${url}"{{if thumbnail_url}} target="_blank"{{/if}}>${name}</a>
            </td>
            <td class="size">${sizef}</td>
        {{/if}}
        <td class="delete">
            <button data-type="${delete_type}" data-url="${delete_url}" class="btn"><i class="icon-remove"/></button>
        </td>
    </tr>
</script>
<script>
$(function () {
    // Initialize the jQuery File Upload widget:
    $('#fileupload').fileupload({
        autoUpload: true,
        url: '<?=fullbase()?>/viewer/uploadattachment?id=<?php echo $this->ticket_id?>'
    });
    $.getJSON("<?=fullbase()?>/viewer/loadattachments?id=<?php echo $this->ticket_id?>", function (files) {
        var fu = $('#fileupload').data('fileupload');
        fu._adjustMaxNumberOfFiles(-files.length);
        fu._renderDownload(files)
            .appendTo($('#fileupload .files'))
            .fadeIn(function () {
                // Fix for IE7 and lower:
                $(this).show();
            });
    });
    // Open download dialogs via iframes, to prevent aborting current uploads:
    $('#fileupload .files a:not([target^=_blank])').live('click', function (e) {
        e.preventDefault();
        $('<iframe style="display:none;"></iframe>')
            .prop('src', this.href)
            .appendTo('body');
    });
});
</script>

