<?include("app/views/scripts/ticket_scripts.phtml");?>
<form class="form-horizontal" action="<?=fullbase()?>/viewer/updatebasic?id=<?=$this->ticket_id?>" method="post">
<div class="page-header">
    <h3><span class="muted"><?php echo $this->ticket_id?></span> / <?=$this->title?></h3>
</div>

<div class="row-fluid">
<div class="span5">
    <legend>Contact</legend>
    <div class="row-fluid">
        <div class="span4">Full Name</div>
        <div class="span8"><?php echo $this->submitter_name?></div>
    </div>
    <div class="row-fluid">
        <div class="span4">Email</div>
        <div class="span8">
            <?php if(!user()->isGuest()) { echo "<a href=\"mailto:".$this->submitter_email."\">".$this->submitter_email."</a>"; } 
            else { echo "<i class=\"icon-lock\"></i>"; } ?>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span4">Phone</div>
        <div class="span8">
            <?php if(!user()->isGuest()) { echo $this->submitter_phone; } else { echo "<i class=\"icon-lock\"></i>"; }?>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span4">CC</div>
        <div class="span8">
            <?if(!user()->isGuest()) { ?>
                <div class="ccarea">
                <?
                include_once("app/views/cc_editor.php");
                cceditor($this->cc);
                ?>
                </div>
                <a class="btn btn-mini" href="#" onclick="addcc($('.ccarea'));return false;"><i class="icon-plus"></i> Add CC</a>
            <?} else { echo "<i class=\"icon-lock\"></i>"; }?>
        </div>
    </div>

    <legend>Details</legend>
    <?php
       if(count($this->metadata) != 0) {
            foreach($this->metadata as $item) {
                echo "<div class=\"row-fluid\">";
                echo "<div class=\"span4\">".$item->key."</div>";
                echo "<div class=\"span8\">".$item->value."</div>";
                echo "</div>";
            }
        }
    ?>

    <div class="row-fluid">
        <div class="span4">Ticket Type</div>
        <div class="span8"><?php echo $this->ticket_type?></div>
    </div>
    <div class="row-fluid">
        <div class="span4">Priority</div>
        <div class="span8"><?php echo $this->priority?></div>
    </div>
    <div class="row-fluid">
        <div class="span4">Status</div>
        <div class="span8"><?php echo $this->status?></div>
    </div>
    <div class="row-fluid">
        <div class="span4">Next Action</div>
        <div class="span8"><?php echo $this->next_action?></div>
    </div>
    <div class="row-fluid">
        <div class="span4">Next Action Deadline</div>
        <div class="span8 <?php echo nadstyle($this->nad)?>"><?php echo $this->nad?></div>
    </div>

</div><!--span-->
<div class="span7">
    <legend>Assignees</legend>
    <?
    foreach($this->teams as $team_id => $team) {
        $out = "";

        $teamname = Footprint::parse($team->team);
        $set = false;
        foreach($team->members as $userid=>$username) {
            if(isset($this->assignees[$userid])) {
                $out .= "<div class=\"assignee\" style=\"width: 60%\">".$username;

                if(isset($this->txlinks[$userid])) {
                    $out .= "<span class=\"sidenote\">";
                    list($extra, $url) = $this->txlinks[$userid];
                    if($url !== null) {
                        $out .= "<a target=\"_blank\" href=\"$url\">$extra</a>";
                    } else {
                        $out .= $extra;
                    }
                    $out .= "</span>";
                }
                $out .= " <span class=\"muted\"> / $teamname</span></div>";
                $set = true;
            }
        }
        if($set) {
            echo $out;
        }
    }
    ?>
    <br>

    <legend>Attachment</legend>
    <?php if(!user()->isGuest()) { 
        include("app/views/scripts/ticket_attachment.phtml");
    } else {
        echo "<i class=\"icon-lock\"></i>";
    } ?>

</div><!--span-->
</div><!--row-fluid-->

<?if(!user()->isGuest()) { ?>
    <legend>New Update</legend>
    <textarea class="description" name="description" onkeypress="checkTab(event);"></textarea>
    <div class="form-actions">
        <button class="btn btn-primary" type="submit" onclick="if($('textarea[name=description]').val().trim() == '') {return confirm('You have not entered any update. Do you really want to submit?');}">Update</button>
        &nbsp;&nbsp;
        <input id="notify1" type="checkbox" name="notify_assignees" value="on" checked=checked"/> <label for="notify1">Notify Assignees</label>
        &nbsp;&nbsp;
        <input id="notify2" type="checkbox" name="notify_submitter" value="on" checked=checked"/> <label for="notify2">Notify Submitter</label>
        &nbsp;&nbsp;
        <input id="notify3" type="checkbox" name="notify_ccs" value="on" checked=checked"/> <label for="notify3">Notify CCs</label>
    </div>
<?}?>

</form>

