<?include("app/views/scripts/ticket_scripts.phtml");?>

<script type="text/javascript" src="<?=fullbase()?>/lib/jquery.focus.js"></script>

<?
if(isset($this->error_messages)) {
    foreach($this->error_messages as $message) {
        echo "<p class=\"errors\"><img align=\"top\" src=\"".fullbase()."/images/exclamation.png\"/> $message</p>";
    }
}
?>

<?if(!isset($form_action)) {
    $form_action = "/viewer/update";
}?>
<form action="<?=fullbase(); echo $form_action?>" method="post">
    <input type="hidden" name="id" value="<?=$this->ticket_id?>"/>
    <input type="text" style="width: 100%" name="title" value="<?=$this->title?>"/>
    <br/>

    <h3>Ticket Detail</h3>
    <table class="ticket_detail" width="100%">
    <tr>
    <td id="submitter">
        <h4>Submitter</h4>

        <div id="populator" style="padding: 3px 0 0 0; background-color: #ddd;">
        <span class="header">Populate From:</span>
        <input type='text' id="careof"/>
        </div>
        <script type="text/javascript">
        $(document).ready(function() {
            $("#careof").autocomplete(persons, {
                mustMatch: true,
                matchContains: true,
                width: 500,
                formatItem: function(row, i, max) {
                    return row.name + "<br/>" + row.email;
                },
                formatMatch: function(row, i, max) {
                    return row.name + " " + row.email;
                },
                formatResult: function(row) {
                    return row.name;
                }
            });
            $("#careof").result(function(event, data, formatted) {
                var tokens = data.name.split(" ");
                var fname = tokens.shift();
                var lname = tokens.join(" ");
                $("input[name=submitter_fname]").val(fname);
                $("input[name=submitter_lname]").val(lname);
                $("input[name=submitter_email]").val(data.email);
                $("input[name=submitter_phone]").val(data.phone);
            });
/*
            $("#submitter").focusin(function() {
                $("#populator").slideDown(); 
            });
            $("#submitter").focusout(function() {
                $("#populator").slideUp(); 
            });
*/
        });
        </script>
     
        <span class="header">First Name:</span>
        <input type="text" value="<?=$this->submitter_fname?>" name="submitter_fname"/>
        <br>

        <span class="header">Last Name:</span>
        <input type="text" value="<?=$this->submitter_lname?>" name="submitter_lname"/>
        <br>

        <span class="header">Email:</span>
        <input type="text" value="<?=$this->submitter_email?>" name="submitter_email"/>
        <br>

        <span class="header">Phone:</span>
        <input type="text" value="<?=$this->submitter_phone?>" name="submitter_phone"/>
        <br>

            
    </td>  
    <td>
        <h4>Routing Information</h4>
        <span class="header">Originating VO:</span>
        <select name="submitter_vo">
        <?
        foreach($this->originating_vos as $id=>$vo) {
            $selected = "";
            $vo_p = Footprint::parse($vo);
            if($vo_p == $this->submitter_vo) $selected = "selected=selected";
            echo "<option value=\"$vo_p\" $selected>$vo_p</option>";
        }
        ?>
        </select>
        <br/>

        <span class="header">Originating Ticket ID:</span>
        <input type="text" value="<?=$this->originating_ticket_id?>" name="originating_ticket_id"/>
        <br/>

        <span class="header">Destination VO:</span>
        <select name="destination_vo">
        <?
        foreach($this->destination_vos as $id=>$vo) {
            $selected = "";
            $vo_p = Footprint::parse($vo);
            if($vo_p == $this->destination_vo) $selected = "selected=selected";
            echo "<option value=\"$vo_p\" $selected>$vo_p</option>";
        }
        ?>
        </select>
        <br/>

        <span class="header">Destination Ticket ID:</span>
        <input type="text" value="<?=$this->destination_ticket_id?>" name="destination_ticket_id"/>
        <br/>
    </td>
    </tr><tr>
    <td>
        <h4>Other Information</h4>
        <span class="header">Ticket Type:</span>
        <select name="ticket_type">
        <?
        $ttype = Footprint::GetTicketTypes();
        foreach($ttype as $type) {
            $selected = "";
            if($type == $this->ticket_type) $selected = "selected=selected";
            echo "<option value=\"$type\" $selected>$type</option>";
        }
        ?>
        </select>
        <br/>

        <span class="header">Priority:</span>
        <select name="priority">
        <?
        $plist = Footprint::GetPriorityList();
        foreach($plist as $id=>$p) {
            $selected = "";
            if($p == $this->priority) $selected = "selected=selected";
            echo "<option value=\"$id\" value=\"$id\" $selected>$p</option>";
        }
        ?>
        </select>
        <br/>

        <span class="header">Status:</span>
        <?
        $style = status2style($this->status);
        echo "<select name=\"status\">";
        foreach(Footprint::GetStatusList() as $status) {
            $selected = "";
            if($status == $this->status) $selected = "selected=selected";
            $style = status2style($status);
            echo "<option value=\"$status\" $selected class='ticketid $style'>$status</option>";
        }
        ?>
        </select>
        <br/>

        <span class="header">Next Action Deadline:</span>
        <input type="text" name="nad" value="<?=$this->nad?>"/>
        <br/>

        <span class="header">Next Action Item:</span>
        <input type="text" name="next_action" value="<?=$this->next_action?>"/>
        <br/>

        <table width="100%">
        <tr>
        <td width="150px"><span class="header">CC:</span></td>
        <td>
            <div class="ccarea">
                <?
                include_once("app/views/cc_editor.php");
                cceditor($this->cc);
                ?>
            </div>
            <a class="button" href="#" onclick="addcc($(this).siblings('div.ccarea'));return false;">Add New CC</a>
        </td>
        </tr></table>
        <br/>
    </td>
    <td width="60%">
        <h4>Assignees:</h4>
        <?
        function showTeams($teams, $assignees, $ids, $txlinks) {
            foreach($ids as $id) {
                $team = $teams[$id];
                echo "<h5>".Footprint::parse($team->team)."</h5>";
                if(sizeof($team->members) > 7) {
                    echo fblist("team_$id", $team->members, $assignees);
                } else {
                    echo checklist("team_$id", $team->members, $assignees, $txlinks);
                }
            }
        }
        echo "<table width=\"100%\">";
        echo "<tr><td>";
        showTeams($this->teams, $this->assignees, config()->editor_teams[0], $this->txlinks);
        echo "</td><td>";
        showTeams($this->teams, $this->assignees, config()->editor_teams[1], $this->txlinks);
        echo "</td><td>";
        showTeams($this->teams, $this->assignees, config()->editor_teams[2], $this->txlinks);
        echo "</td></tr>";
        echo "</table>";
        ?>
    </td>
    </tr></table>

    <span class="header">New Update:</span>
    <select name="quickdesc" onchange="
        if($(this).val()) {
            $('.resizable').val('Loading...');
            $.ajax({
                url: '<?=fullbase()?>/viewer/quickdesc?id='+escape($(this).val()),
                success: function(data) {
                    $('.resizable').val(data);
                }
            });
        }
        ">  
    <?
    $model = new Schema();
    $descs = $model->getquickdesc();
    echo "<option value=\"\">(Quick Description)</option>";
    foreach($descs as $name=>$desc) {
        echo "<option value=\"$name\">$name</option>";
    }
    ?>
    </select>
    <textarea class="resizable" style="width: 98%" rows="5" name="description" onkeypress="checkTab(event);"><?=$this->description?></textarea>
    <br/>

    <?if(!isset($submit_label)) {
        $submit_label = "Update";
    }?>
    <input type="submit" value="&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?=$submit_label?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"/>

    <?if(isset($suppression_control)) {?>
        &nbsp;&nbsp;
        <input id="notify1" type="checkbox" name="notify_assignees" value="on" checked=checked"/> <label for="notify1">Notify Assignees</label>
        &nbsp;&nbsp;
        <input id="notify2" type="checkbox" name="notify_submitter" value="on" checked=checked"/> <label for="notify2">Notify Submitter</label>
        &nbsp;&nbsp;
        <input id="notify3" type="checkbox" name="notify_ccs" value="on" checked=checked"/> <label for="notify3">Notify CCs</label>

        &nbsp;&nbsp;
        <input id="closewindow" type="checkbox" name="closewindow" value="on"/> <label for="closewindow">Close Window</label>
    <?}?>

    <br/>
    <br/>

</form>

