<?include("app/views/scripts/ticket_scripts.phtml");?>
<style>
.form-horizontal .control-label {
padding-top: inherit;
font-size:90%;
color:#666;
}
label {
margin-bottom: 0px;
}
.controls {
line-height: 18px;
}
</style>

<form class="form-horizontal" action="<?=fullbase()?>/viewer/updatebasic?id=<?=$this->ticket_id?>" method="post">
<div class="page-header">
    <h3><span class="muted"><?php echo $this->ticket_id?></span> / <?=$this->title?></h3>
</div>

<div class="row-fluid">
<div class="span5">
    <legend>Contact</legend>
    <div class="control-group">
        <label class="control-label">Full Name</label>
        <div class="controls"><?php echo $this->submitter_name?></div>
    </div>
    <div class="control-group">
        <label class="control-label">Email</label>
        <div class="controls">
            <?php if(!user()->isGuest()) { echo "<a href=\"mailto:".$this->submitter_email."\">".$this->submitter_email."</a>"; } 
            else { echo "<i class=\"icon-lock\"></i>"; } ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Phone</label>
        <div class="controls">
            <?php if(!user()->isGuest()) { echo $this->submitter_phone; } else { echo "<i class=\"icon-lock\"></i>"; }?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">CC</label>
        <div class="controls">
            <?if(!user()->isGuest()) { ?>
                <div class="ccarea">
                <?
                include_once("app/views/cc_editor.php");
                cceditor($this->cc);
                ?>
                </div>
                <a class="btn btn-mini" href="#" onclick="addcc($('.ccarea'));return false;"><i class="icon-plus"></i> Add CC</a>
            <?} else { echo "<i class=\"icon-lock\"></i>"; }?>
        </div>
    </div>

    <legend>Details</legend>
    <?php
        foreach($this->metadata as $key=>$value) {
            if($value === null) continue;
            //suppress metadata ID field (just show textual)
            $label = "";
            switch($key) {
            case "SUPPORTING_SC_NAME":
                $label = "Support Center"; break;
            case "ASSOCIATED_VO_NAME":
                $label = "Associated VO"; break;
            case "ASSOCIATED_R_NAME":
                $label = "Resource Name"; break;
            case "SUBMITTED_VIA":
                $label = "Submitted Via"; break;
            case "SUBMITTER_NAME":
                $label = "Submitter"; break;
            case "ticket_links":
                $label = "Ticket Links";
                $html = "<ul>";
                foreach(explode(",", $value) as $id) {
                    $info = $this->ticket_links_info[$id];
                    $title = $this->escape($info->title);
                    $html .= "<li><a target='_blank' href='".fullbase()."/$id'><b>$id</b> $title</a></li>";
                }
                $value = $html."</ul>";
                break;
            }
            if($label != "") {
                echo "<div class=\"control-group\">";
                echo "<label class=\"control-label\">$label</label>";
                echo "<div class=\"controls\">".$value."</div>";
                echo "</div>";
            }
        }
    ?>

    <div class="control-group">
        <label class="control-label">Ticket Type</label>
        <div class="controls"><?php echo $this->ticket_type?></div>
    </div>
    <div class="control-group">
        <label class="control-label">Priority</label>
        <div class="controls"><?php echo $this->priority?></div>
    </div>
    <div class="control-group">
        <label class="control-label">Status</label>
        <div class="controls"><?php echo $this->status?></div>
    </div>
    <div class="control-group">
        <label class="control-label">Next Action</label>
        <div class="controls"><?php echo $this->next_action?></div>
    </div>
    <div class="control-group">
        <label class="control-label">Next Action Deadline</label>
        <div class="controls <?php echo nadstyle($this->nad)?>"><?php echo $this->nad?></div>
    </div>

</div><!--span-->
<div class="span7">
    <legend>Assignees</legend>
    <?
    foreach($this->teams as $team_id => $team) {
        $out = "";

        $teamname = Footprint::parse($team->team);
        $set = false;
        foreach($team->members as $userid=>$username) {
            if(isset($this->assignees[$userid])) {
                $out .= "<div class=\"assignee\" style=\"width: 60%\">".$username;

                if(isset($this->txlinks[$userid])) {
                    list($extra, $url) = $this->txlinks[$userid];
                    if($url !== null) {
                        $out .= "&nbsp;<a target=\"_blank\" href=\"$url\">$extra</a>";
                    } else {
                        $out .= "$extra&nbsp;";
                    }
                }
                $out .= " <span class=\"muted\"> / $teamname</span></div>";
                $set = true;
            }
        }
        if($set) {
            echo $out;
        }
    }
    ?>
    <br>

    <legend>Assignees</legend>
    TODO
    <br>

    <?php if(!user()->isGuest()) { 
        include("app/views/scripts/ticket_attachment.phtml");
    } else {
        include("app/views/scripts/ticket_attachment_ro.phtml");
    } ?>

</div><!--span-->
</div><!--row-fluid-->

<?if(!user()->isGuest()) { ?>
    <legend>New Update</legend>
    <textarea class="description" name="description" onkeypress="checkTab(event);"></textarea>
    <div class="form-actions">
        <button class="btn btn-primary" type="submit" onclick="if($('textarea[name=description]').val().trim() == '') {return confirm('You have not entered any update. Do you really want to submit?');}">Update</button>
        &nbsp;&nbsp;
        <input id="notify1" type="checkbox" name="notify_assignees" value="on" checked=checked"/> <label for="notify1">Notify Assignees</label>
        &nbsp;&nbsp;
        <input id="notify2" type="checkbox" name="notify_submitter" value="on" checked=checked"/> <label for="notify2">Notify Submitter</label>
        &nbsp;&nbsp;
        <input id="notify3" type="checkbox" name="notify_ccs" value="on" checked=checked"/> <label for="notify3">Notify CCs</label>
    </div>
<?}?>

</form>

