<div class="yourinfo">
<div class="row-fluid">
<?php
$rl = "<span class=\"muted\">* Required</span>";
?>
<?php if(user()->allows("update")) { ?>
    <div class="span3 contact_populator">
    <label for="careof">Populate From</label>
    <?php  echo "<input type='text' id=\"careof\"/>"; ?>
    </div>
    <div class="span3"><?=$this->element->name?></div>
    <div class="span3"><?=$this->element->email?></div>
    <div class="span3"><?=$this->element->phone?></div>
<? } else { ?>
    <div class="span4"><?=$this->element->name?></div>
    <div class="span4"><?=$this->element->email?></div>
    <div class="span4"><?=$this->element->phone?></div>
<?php } ?>
</div><!--row-->
</div><!--yourinfo-->

<?if(user()->allows("admin")) {?>
<script type="text/javascript">
$(document).ready(function() {
    $("#careof").autocomplete(persons, {
        mustMatch: true,
        matchContains: true,
        width: 500,
        formatItem: function(row, i, max) {
            return row.name+ "<br/>Email: " + row.email;
        },
        formatMatch: function(row, i, max) {
            return row.name+ " " + row.email;
        },
        formatResult: function(row) {
            return row.name;
        }
    });
    $("#careof").result(function(event, data, formatted) {
        $("#name").val(data.name);
        $("#email").val(data.email);
        $("#phone").val(data.phone);
        $("#vo_id").val(-1); //reset vo to i-don-know
    });
});
</script>
<?php } ?>
