<h3>Contact Information</h3>
Primary contact for this ticket (usually you).<br/>
<table>
<tr>
<td>
<?=$this->element->name?>
<?=$this->element->email?>
<?=$this->element->phone?>
<?=$this->element->vo_id?>

</td>
<?  if(user()->allows("update")) { ?>
    <td style="vertical-align: middle;">
    <img src="<?=base()?>/images/populator_arrow.png">
    </td>
    <td style="vertical-align: middle;">
    <div class="contact_populator">
    Populate from someone else's contact information<br/>
    <label class="required" for="careof">Name</label><br/>
    <?
    echo "<input type='text' id=\"careof\"/>";
    ?>
    </div>
    </td>
    <?
}
?>
</table>
<?if(!user()->isguest()) { ?>
    <dt>CC this ticket to following email address</dt>
    <dd>
        <div class="ccarea" style="width:270px">
            <?
            $ccs = array();
            if(Zend_Registry::isRegistered("passback_ccs")) {
                $ccs = Zend_Registry::get("passback_ccs");
            }
            include_once("app/views/cc_editor.php");
            cceditor($ccs);
            ?>
        </div>
        <a class="button" href="#" onclick="addcc($(this).siblings('div.ccarea'));return false;">Add New CC</a>
    </dd>
    <br/>
<?} else {?>
    <h3>Public Submission</h3>
    <p>You have not provided OIM registered x509 certificate.</p>
    <?=$this->element->captcha?>
<?}?>

<?if(user()->allows("admin")) {?>
<script type="text/javascript">
$(document).ready(function() {
    $("#careof").autocomplete(persons, {
        mustMatch: true,
        matchContains: true,
        width: 500,
        formatItem: function(row, i, max) {
            return row.name+ "<br/>Email: " + row.email;
        },
        formatMatch: function(row, i, max) {
            return row.name+ " " + row.email;
        },
        formatResult: function(row) {
            return row.name;
        }
    });
    $("#careof").result(function(event, data, formatted) {
        $("#name").val(data.name);
        $("#email").val(data.email);
        $("#phone").val(data.phone);
        $("#vo_id").val(-1); //reset vo to i-don-know
    });
});
</script>
<?php } ?>


