<form action="<?=$this->escape($this->element->getAction())?>"
      method="<?=$this->escape($this->element->getMethod())?>">
<dl>

<?=$this->render("yourinfo.phtml", true)?>

<h3>Issue Detail</h3>
<?=$this->element->title?>

<br/>
<dt>
<label class="required" for="title">Select following check boxes to open this ticket in CRITICAL priority</label>
</dt>
<?
function checked($e)
{
    if($e->checked) return "checked=checked";
}
?>
<p>
    <input type="hidden" name="critical_1" value="0">
    <input type="checkbox" name="critical_1" id="critical_1" value="1" <?=checked($this->element->critical_1)?>>
This issue needs immediate, undivided attention from GOC staff until resolved.<br/>
</p>

<p>
    <input type="hidden" name="critical_2" value="0">
    <input type="checkbox" name="critical_2" id="critical_2" value="1" <?=checked($this->element->critical_2)?>>
Contact will be available immediately for contact by GOC staff for details regarding the reported problem.<br/>
</p>
<div class="indent">
    * Problems that are not related to an immediate security threat or a GOC critical service outage will be handled during normal business hours.
</div>
<br/>
<?=$this->render("what_does_critical_mean.phtml", true)?>

<?=$this->element->detail?>
<br/><br/>

<?=$this->element->captcha?>
<?=$this->element->submit_button?>
</dl>
</form>

