<?
echo "<"."?xml version=\"1.0\" encoding=\"UTF-8\"?".">\n";
?>
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9"
         xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<?
    foreach($this->tickets as $ticket) {
        $id = $ticket->mrid;
        $url = fullbase()."/viewer?id=".$id;

        $freq = "daily";
        if($ticket->mrstatus == "Closed") $freq = "monthly";
?>
   <url>
      <loc><?=$url?></loc>
      <changefreq><?=$freq?></changefreq>
   </url>
<?
    }
?>
</urlset>

