<?include("app/views/scripts/header.phtml");?>
<div class="bread"><a href="<?=base()?>">Home</a> &gt; This process or following up on an already submitted request</div>
<div class="form">
<p>If you have questions regarding this process or would like to follow up on your request please contact the OSG GOC at<br/>
<a href="mailto:help@opensciencegrid.org">help@opensciencegrid.org</a><br/>
or call 317-278-9699.</p>
</div>
<?include("app/views/scripts/footer.phtml");?>
