<?php echo $this->render("bootheader.phtml", true);?>
<div class="container-fluid">
<?php echo $this->alerts();?>
<div class="page-header"><h2><?php echo $this->page_title?></h2></div>

<style>
#table td {
padding-right: 5px;
}
.delete {
cursor: pointer;
}
</style>

<p class="help-block">Following assingment override will be applied during next assignee calculation.</p>

<form action="override/submit" method="post">
<table id="table" class="table">
<thead>
<tr><th>From</th><th>To</th><th></th></tr>
</thead>
<tbody>
<?
$id = 0;
foreach($this->overrides as $from=>$to) {
    echo "<tr>";
    echo "<td><input name=\"rec_from[${id}]\" type=\"text\" value=\"$from\"/></td>";
    echo "<td><input name=\"rec_to[${id}]\" type=\"text\" value=\"$to\"/></td>";
    echo "<td><img src=\"images/delete.png\" class=\"delete\"/></td>";
    echo "</tr>";
    $id++;
}
?>
</tbody>
</table>
<p><a class="btn" href="javascript:void(0)" onclick="add();">Add New Override</a></p>

<div class="form-actions">
<button type="submit" name="submit_button" class="btn btn-primary btn-large" id="submit_button">Submit</button>
</div>

</form>

<script type="text/javascript">
var nextid = <?=$id?>;
function add() {
    $("#table").append("<tr><td><input name='rec_from["+nextid+"]' type='text'/></td><td><input name='rec_to["+nextid+"]' type='text'/></td><td><img src='images/delete.png' class='delete'/></td></tr>");
    setup_input();
    nextid++;
}
var assignees = [
<?
$first = true;
foreach($this->users as $id=>$name) {
    if(!$first) {
        echo ",\n";
    } else {
        $first = false;
    }
    echo "{ name: \"$name\", id: \"$id\"}";
}
?>
]

function setup_input() {
   $("input").autocomplete(assignees, {
        mustMatch: true,
        matchContains: true,
        width: 500,
        formatItem: function(row, i, max) {
            return row.name + "<br/>ID:" + row.id;
        },
        formatMatch: function(row, i, max) {
            return row.name + " " + row.id;
        },
        formatResult: function(row, i, max) {
            return row.id;
        }
    }); 
    $(".delete").click(function() {
        $(this).parents("tr").remove();
    });
}

$(document).ready(function() {
    setup_input();
});
</script>

<?php echo $this->render("pagefooter.phtml", true);?>
</div><!--container-fluid-->
<?php echo $this->render("bootfooter.phtml", true);?>


