<?php
header("content-type: text/plain");
foreach($this->suggests as $suggest) {
    echo $suggest."\n";
}

/* Sample result object content
object(stdClass)#59 (3) {
  ["responseHeader"]=>
  object(stdClass)#58 (3) {
    ["status"]=>
    int(0)
    ["QTime"]=>
    int(4)
    ["params"]=>
    object(stdClass)#57 (8) {
      ["facet"]=>
      string(4) "true"
      ["fl"]=>
      string(8) "id,title"
      ["facet.mincount"]=>
      string(1) "1"
      ["q"]=>
      string(3) "*:*"
      ["facet.prefix"]=>
      string(5) "froze"
      ["facet.field"]=>
      string(4) "text"
      ["wt"]=>
      string(4) "json"
      ["rows"]=>
      string(1) "0"
    }
  }
  ["response"]=>
  object(stdClass)#42 (3) {
    ["numFound"]=>
    int(1755)
    ["start"]=>
    int(0)
    ["docs"]=>
    array(0) {
    }
  }
  ["facet_counts"]=>
  object(stdClass)#41 (4) {
    ["facet_queries"]=>
    object(stdClass)#40 (0) {
    }
    ["facet_fields"]=>
    object(stdClass)#39 (1) {
      ["text"]=>
      array(8) {
        [0]=>
        string(6) "frozen"
        [1]=>
        int(1)
        [2]=>
        string(34) "frozen.showers.dbrelease.v16080101"
        [3]=>
        int(1)
        [4]=>
        string(32) "frozen.showers.dbrelease.v170602"
        [5]=>
        int(1)
        [6]=>
        string(32) "frozen.showers.dbrelease.v180601"
        [7]=>
        int(1)
      }
    }
    ["facet_dates"]=>
    object(stdClass)#38 (0) {
    }
    ["facet_ranges"]=>
    object(stdClass)#37 (0) {
    }
  }
}


*/
