<?php echo $this->render("bootheader.phtml", true);?>

<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.1/css/jquery.dataTables.css" />
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/fixedheader/2.1.2/css/dataTables.fixedHeader.css" />
<script type="text/javascript" src="//cdn.datatables.net/1.10.1/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="//cdn.datatables.net/fixedheader/2.1.2/js/dataTables.fixedHeader.min.js"></script>

<style>
.search {
width: 100%;
position: relative;
left: -15px;
}
</style>

<div class="container-fluid ticket-list">
<?php echo $this->alerts(); ?>

<span class="pull-right">
    <a type="application/rss+xml" href="<?php echo fullbase()?>/rss">
    <i class="fa fa-rss-square fa-2x"></i></a>
</span>

<?php
echo "<ul class=\"nav nav-tabs\">";
$active = "";
if($this->submenu_selected == "listopen") { 
    $active = "active"; 
}
echo "<li class=\"$active\">";
echo "<a href=\"list/open\">Open Tickets</a>";
echo "</li>";

$active = "";
if($this->submenu_selected == "listrecentclose") { $active = "active"; }
echo "<li class=\"$active\">";
echo "<a href=\"list/recentclose\">Recently Closed Tickets</a>";
echo "</li>";

echo "</ul>";

$columns = array(
    array("name"=>"ID", "type"=>"numeric", "visible"=>true), 
    array("name"=>"Submitter", "type"=>"string", "meta"=>true, "visible"=>false),
    array("name"=>"Submit Date", "type"=>"date", "visible"=>false),
    array("name"=>"Title", "type"=>"html", "visible"=>true), 
    array("name"=>"Type", "type"=>"string", "visible"=>true), 
    array("name"=>"Update Date", "type"=>"date", "visible"=>false), 
    array("name"=>"Next Action", "type"=>"string", "visible"=>true), 
    array("name"=>"NAD", "type"=>"html", "visible"=>true), 
    array("name"=>"Priority", "type"=>"html", "visible"=>true), 
    array("name"=>"Assignees", "type"=>"html", "visible"=>true), 
    array("name"=>"CCs", "type"=>"html", "visible"=>true), 

    array("name"=>"Resource", "type"=>"string", "meta"=>true, "visible"=>false),
    array("name"=>"Resource Group", "type"=>"string", "meta"=>true, "visible"=>false),
    array("name"=>"Support Center", "type"=>"string", "meta"=>true, "visible"=>false),
    array("name"=>"Virtual Organization", "type"=>"string", "meta"=>true, "visible"=>false),
    array("name"=>"Submitted Via", "type"=>"string", "meta"=>true, "visible"=>false),
    array("name"=>"GGUS Ticket Type", "type"=>"numeric", "meta"=>true, "visible"=>false),
    array("name"=>"GGUS Ticket ID", "type"=>"numeric", "meta"=>true, "visible"=>false),

    array("name"=>"SNOW Ticket ID", "type"=>"string", "meta"=>true, "visible"=>false)

    //not yet published.. (anyone wants to see these?)
    //array("name"=>"GGUS Ticket Type", "type"=>"string", "meta"=>true, "visible"=>false),
    //array("name"=>"GGUS Problem Type", "type"=>"string", "meta"=>true, "visible"=>false),
);


$tickets = $this->tickets;
$metadata = $this->metadata;

?>
<table cellpadding="0" cellspacing="0" border="0" class="display" id="tickets">
<thead>
    <tr>
    <?php
    foreach($columns as $cid=>$column) {
        echo "<th>";
        echo str_replace(" ", "&nbsp;", $column["name"]);
        echo "<input data-pos=\"$cid\" type=\"text\" class=\"search\"/>";
        echo "</th>";
    }?>
    </tr>
</thead>

<?php

function td($html = "", $escape = true) {
    if(!$html) {
        echo "<td><span class=\"muted\">N/A</span></td>";
    } else {
        if($escape) {
            echo "<td>".htmlentities($html)."</td>";
        } else {
            echo "<td>$html</td>";
        }
    }
}

$model = new Schema();
$teams = $model->getteams();
$aka_model = new AKA();

foreach($tickets as $ticket) {
    if($ticket->tickettype == "Security") {
        if(!user()->allows("view_security_incident_ticket")) {
            //don't show security ticket to unauthorized users
            continue;
        } 
    }

    $url = base()."/".$ticket->mrid;
    $target = "ticket_".$ticket->mrid;

    //assignee, cc
    $assignees = array();
    $ccs = array();
    foreach(explode(" ", trim($ticket->mrassignees)) as $a) {
        //FP somehow put CCs on assginee field...-
        if(strlen($a) >= 3 and strpos($a, "CC:") === 0) {
            $ccs[] = substr($a, 3);
            continue;
        }
        //FP somehow contains team names on assignee... ignore it
        $team_name = false;
        foreach($teams as $team) {
            if($team->team == $a) {
                $team_name = true;
                break;
            }
        }
        if($team_name) continue;

        //store to assignee list
        $aka = $aka_model->lookupName($a);
        $assignees[$a] = str_replace(" ", "&nbsp;", $aka);
    }
    //dlog(explode(" ", trim($ticket->mrassignees)), "assignees");

    //priority
    $priority = Footprint::getPriority($ticket->mrpriority);
    switch($ticket->mrpriority) {
    case 3: $priority = "<font color='#c90'>$priority</font>"; break;
    case 2: $priority = "<font color='red'>$priority</font>"; break;
    case 1: $priority = "<font color='red'>$priority</font>"; break;
    }

    //nad
    $nad_unix = strtotime($ticket->nad);
    $nad = date("Y-m-d", $nad_unix);
    if($nad_unix < time()) {
        $nad = "<font color='red'>$nad</font>";
    } else if($nad < time() + 3600*config()->nad_alert_hours) {
        $nad = "<font color='#c90'>$nad</font>";
    }

    //dates
    //for some reason, datatable doesn't sort the date correctly if there is timestamp on it.. just show date
    $submit_date = substr($ticket->mrsubmitdate, 0, 10);
    $update_date = substr($ticket->mrupdatedate, 0, 10);

    $title = $ticket->mrtitle;

    $tickettype = Footprint::parse($ticket->tickettype);
    //if($tickettype == "") $tickettype = "&nbsp"; //if empty, datatables col filter will mulfunction

    $submitter = null; //"N/A"; //if empty, datatables col filter will mulfunction
    if(isset($metadata[$ticket->mrid]["SUBMITTER_NAME"])) {
        $submitter = $metadata[$ticket->mrid]["SUBMITTER_NAME"];
    }

    $submitted_via = null; //"N/A"; //if empty, datatables col filter will mulfunction
    if(isset($metadata[$ticket->mrid]["SUBMITTED_VIA"])) {
        $submitted_via = $metadata[$ticket->mrid]["SUBMITTED_VIA"];
    }

    $resource_group = null; //"N/A"; //if empty, datatables col filter will mulfunction
    if(isset($metadata[$ticket->mrid]["ASSOCIATED_RG_NAME"])) {
        $resource_group = $metadata[$ticket->mrid]["ASSOCIATED_RG_NAME"];
    }

    $ggus_ticket_id = null; //"N/A"; //if empty, datatables col filter will mulfunction
    if(isset($metadata[$ticket->mrid]["GGUS_TICKET_ID"])) {
        $ggus_ticket_id = $metadata[$ticket->mrid]["GGUS_TICKET_ID"];
    }

    $ggus_ticket_type = null; //"N/A"; //if empty, datatables col filter will mulfunction
    if(isset($metadata[$ticket->mrid]["GGUS_TICKET_TYPE"])) {
        $ggus_ticket_type = $metadata[$ticket->mrid]["GGUS_TICKET_TYPE"];
    }

    $resource = null; //"N/A"; //if empty, datatables col filter will mulfunction
    if(isset($metadata[$ticket->mrid]["ASSOCIATED_R_NAME"])) {
        $resource = $metadata[$ticket->mrid]["ASSOCIATED_R_NAME"];
    }

    $sc = null; //"N/A"; //if empty, datatables col filter will mulfunction
    if(isset($metadata[$ticket->mrid]["SUPPORTING_SC_NAME"])) {
        $sc = $metadata[$ticket->mrid]["SUPPORTING_SC_NAME"];
    }

    $vo = null; //"N/A"; //if empty, datatables col filter will mulfunction
    if(isset($metadata[$ticket->mrid]["ASSOCIATED_VO_NAME"])) {
        $vo = $metadata[$ticket->mrid]["ASSOCIATED_VO_NAME"];
    }

    $snow_ticket_id = null; // "N/A"; //if empty, datatables col filter will mulfunction
    if(isset($metadata[$ticket->mrid]["SERVICENOW_TICKET_ID"])) {
        $snow_ticket_id = $metadata[$ticket->mrid]["SERVICENOW_TICKET_ID"];
    }
    ?>
    <tr onclick="window.name = 'gocticket_list'; window.open('<?=$url?>','<?=$target?>');">
    <?php
    td($ticket->mrid);
    td($submitter);
    td($submit_date);
    td($title, false);
    td($tickettype);
    td($update_date);
    td($ticket->nextaction);
    td($nad, false);
    td($priority, false);
    td(implode("<br>", $assignees), false);
    if(!user()->isguest()) {
        echo "<td>".implode(" | ", $ccs)."<br></td>";
    } else {
        echo "<td>(Hidden)</td>";
    }
    td($resource);
    td($resource_group);
    td($sc);
    td($vo);
    td($submitted_via);
    td($ggus_ticket_type);
    td($ggus_ticket_id);
    td($snow_ticket_id);
    echo "</tr>";
}
?>  
</table>

<script>

$.cookie.json = true;
var colsearch = $.cookie('colsearch');
if(colsearch == undefined) {
    colsearch = {};
}

<?php
$aocolumns = array();
foreach($columns as $cid=>$column) {
    $visible = false;
    if($column["visible"]) {
        $visible = true;
    }
    $aocolumns[] = array("sType"=>$column["type"], "bVisible"=>$visible);
}
?>

var dtable = $('#tickets').dataTable({
    //"bJQueryUI": true,
    "bAutoWidth": true,
    "bPaginate": false,
    "bStateSave": true,
    //"bInfo": true,
    //"sCookiePrefix": "<?php echo $this->dt_cookie_prefix?>",
    //"iCookieDuration": 60*60*24*90, /*90 days*/
    "sDom": '<"toolbar">frtip',
    "aoColumns": <?php echo json_encode($aocolumns);?>
});

function fnShowHide(button, iCol )
{
    $(button).toggleClass("active");
    var bVis = dtable.fnSettings().aoColumns[iCol].bVisible;
    dtable.fnSetColumnVis( iCol, bVis ? false : true );
    init_colsearch(); //reinit
}

//need to injext toolbar into data table..
$(".toolbar").html('<?

    //split normal v.s. metadata column
    $normal_column = "";
    $meta_column = "";
    foreach($columns as $cid=>$column) {
        $name = $column["name"];

        /*
        if(isset($this->table_cols[$cid])) {
                if($this->table_cols[$cid] == false) { $active = ""; }
        } else {
                if($column["visible"] == false) { $active = ""; }
        }
        */

        if(isset($column["meta"])) {
            $meta_column .= "<li class=\"coltog\" data-cid=\"$cid\" onclick=\"fnShowHide(this, $cid); return false;\"><a href=\"#\">$name</a></li>";
        } else {
            $normal_column .= "<li class=\"coltog\" data-cid=\"$cid\" onclick=\"fnShowHide(this, $cid); return false;\"><a href=\"#\">$name</a></li>";
        }
    }

    //display metadata column
    echo "<div class=\"navbar navbar-inverse\">";
    echo "<div class=\"navbar-inner\">";
    echo "<div class=\"container\">";

    echo "<ul class=\"nav\">";
    echo $normal_column;
    echo "<li class=\"divider-vertical\"></li>";
    echo "<li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Metadata <b class=\"caret\"></b></a>";
    echo "<ul class=\"dropdown-menu\">";
    echo $meta_column;
    echo "</ul>";//dropdow
    echo "</li>";//metadata menu

    echo "</ul>";//nav

    echo "</div>";//container
    echo "</div>";//navbar-inner
    echo "</div>";//navbar
?>');

function init_colsearch() {
    $(".search").each(function(idx, it) {
        var cid = $(it).data('pos');
        if(colsearch[cid] != undefined) {
            $(it).val(colsearch[cid]);
            dtable.fnFilter(colsearch[cid], cid); //reapply anyway..
        } else {
            dtable.fnFilter("", cid); //reset (datatable sometimes remebers old value and try to filter it..)
        }
        //remember colsearch
        function update() {
            var tvalue = jQuery.trim(it.value);
            dtable.fnFilter(tvalue, cid);
            colsearch[cid] = tvalue;
            $.cookie('colsearch', colsearch, {expires: 30, path: window.location.pathname});
        }
        $(it).keyup(update);
        $(it).bind("input", update);//for IE's X button in text input

        //prevent sorting to fire when user clicks on the search box
        $(it).click(function(e) {
            e.cancelBubble = true;
            $(it).focus();
            return false;
        });
    });
}

$(function() {
    init_colsearch();

    //activate visiable column
    $(".coltog").each(function(i, it) {
        var cid = $(it).data('cid');
        var bVis = dtable.fnSettings().aoColumns[cid].bVisible;
        if(bVis) {
            $(it).addClass("active");
        }
    });

    //show after table table is initialized
    $(".ticket-list").show();
});
</script>

<?php echo $this->render("pagefooter.phtml", true);?>
</div><!--container-fluid-->
<?php echo $this->render("bootfooter.phtml", true);?>
