<?include("app/views/scripts/header.phtml");?>
<div class="bread">You are here &gt; <a href="<?=base()?>/admin"><?=submenutitle($this->submenu_selected)?></a> &gt; Find Error</div>

<h3>Open Tickets with no GOC member assignments</h3>
<?
if(count($this->na_assignments) == 0) {
    echo "<p>Congulatulations. All ticket has GOC member assignments.</p>";
} else {
    foreach($this->na_assignments as $na) {
        echo "<p><a href=\"".fullbase()."/".$na->mrid."\" style='color:red;'>".$na->mrid.": ".$na->mrtitle."</a></p>";
    }
    echo "<blockquote>In order to fix this issue, assign at least one GOC member to these tickets via FP.";
    echo "</blockquote>";
}

echo "<h3>Team Dump</h3>";
echo "<blockquote>Please note that the team information is cached for about 10 minutes</blockquote>";
echo "<p>";
foreach($this->teams as $team_entry) {
    $team = Footprint::parse($team_entry->team);
    if( $team == "OSG GOC Support Team" || 
        $team == "OSG Operations Infrastructure" || 
        $team == "OSG GOC Management" ||
        $team == "OSG Security Coordinators" ||
        $team == "OSG Storage Team") {
        echo "<h4>$team</h4>";
        echo $team_entry->members;
    }
}
echo "</p>";
?>
<br/><br/>

<h3>OIM/FP Match</h3>
<blockquote>
<p>GOC Ticket submitter pulls information from OIM and submit tickets on FP system which means that certain types of information needs to be synchronized in order to prevent melt down of the system (or I should say, un-defined behavior..) </p>
<p>
Following lists shows any records that needs to be synclonized and they are marked in <font color='red'>RED</font>. If you don't see any notes in red, everything is synchronized correctly.
</p>
<p>
Here is how it works.. First, GOC Ticket pulls information from OIM. Each records in OIM has a field called "footprints_id" which are the FP counterpart of that record. GOC Ticket forms uses that footprint_id values to submit ticket to FP.
</p>
<br/>
<p>
<font color='red'>only in oim</font> means that the record is in OIM but not yet added to the FP. Please go to FP/administration page and add that value to appropriate schema. It could be, that you just need to remove that value from OIM.
</p>
<p>
<font color='red'>only in fp</font> means that the record is in FP but either it doesn't exist in OIM or mapping for footprints_id is not correct. If could also means that the record needs to be removed from FP.
</p>
<br/>
<p>More instructions below..</p>
</blockquote>

<h3>Originating VOS</h3>
<table>
<tr><th>OIM(footprints_id)</th><th>Footprint</th><th></th></tr>
<?
foreach($this->error_origvos as $error) {
    $note = $error[0];
    $fp = $error[1];
    $oim = $error[2];
    echo "<tr><td>$oim</td><td>$fp</td><td><font color='red'>$note</font></td></tr>";
}
?>
</table>
<blockquote>
<p>In order to update these entries on OIM, go to (TODO: currently OIM doesn't allow users to update this)</p>
<p>In order to update the list of VOs on FP, go to Footprints &gt; Administration &gt; Project &gt; Field Maintenance &gt; Select "Originating VO Support Center", click EDIT. Do the same process for "Destination VO Support Center".</p>
</blockquote>

<h3>Destination VOS</h3>
<table>
<tr><th>OIM(footprints_id)</th><th>Footprint</th><th></th></tr>
<?
foreach($this->error_destvos as $error) {
    $note = $error[0];
    $fp = $error[1];
    $oim = $error[2];
    echo "<tr><td>$oim</td><td>$fp</td><td><font color='red'>$note</font></td></tr>";
}
?>
</table>
<blockquote>
<p>In order to update these entries on OIM, go to (TODO: currently OIM doesn't allow users to update this)</p>
<p>In order to update the list of VOs on FP, go to Footprints &gt; Administration &gt; Project &gt; Field Maintenance &gt; Select "Destination VO Support Center", click EDIT</p>
</blockquote>

<h3>Support Centers</h3>
<table>
<tr><th>OIM(footprints_id)</th><th>Footprint</th><th></th></tr>
<?
foreach($this->error_sc as $error) {
    $note = $error[0];
    $fp = $error[1];
    $oim = $error[2];
    echo "<tr><td>$oim</td><td>$fp</td><td><font color='red'>$note</font></td></tr>";
}
?>
</table>
<blockquote>
<p>In order to update these entries on OIM, go to (TODO: currently OIM doesn't allow users to update this)</p>
<p>In order to update the list of VOs on FP, go to Footprints &gt; Administration &gt; Project &gt; Add Agents / Edit Agents</p>
</blockquote>

<h3>Email Address</h3>
<table>
<tr><th>OIM</th><th>Footprint</th><th></th></tr>
<?
foreach($this->error_email as $error) {
    $oim_sc = $error[0];
    $oim_email  = $error[1];
    $fp_sc = $error[2];
    $fp_email  = $error[3];
    $note = $error[4];
    echo "<tr><td>$oim_sc($oim_email)</td><td>$fp_sc($fp_email)</td><td><font color='red'>$note</font></td></tr>";
}
?>
</table>
<blockquote>
<p>In order to update these entries on OIM, go to OIM / SC. Find the SC, change the Primary Operations Contact or if the correct contact is selected, go to Contact page for that contact to update the email address</p>
<p>In order to update the list of VOs on FP, go to Footprints &gt; Administration &gt; Project &gt; Add Agents / Edit Agents, select Agent, click GO, and look under primary email address</p>
</blockquote>

<h3>Resource To Support Center Link</h3>
<table>
<tr><th>Resource Name(Resource ID)</th><th>Footprint SC(SC ID)</th><th></th></tr>
<?
foreach($this->resource_sclink as $rec) {
    $note = $rec["note"];
    $name = $rec["resource_name"];
    $id = $rec["resource_id"];
    $sc_id = $rec["sc_id"];
    $sc_name = $rec["sc_name"];
    echo "<tr><td>$name($id)</td><td>$sc_name($sc_id)</td><td><font color='red'>$note</font></td></tr>";
}
?>
</table>
<blockquote>
<p>When user submit issue specific to Resource, gocticket app tries to find a corresponding support center. The view used to do this lookup relies on resource_group to be active for the resource (resource group is tied to SC), and if this is not the case the lookup will fail. There might be other reasons that this could fail also.. If the lookup fails, the OSG-GOC will be used as SC.</p>
</blockquote>


<?include("app/views/scripts/footer.phtml");?>


