<?php echo $this->render("bootheader.phtml", true);?>
<div class="container-fluid">

<?php
$form_action = "custom/submit";
$submit_label = "Submit";

echo $this->alerts();
echo "<div class=\"page-header\"><h2>".$this->page_title."</h2></div>";

echo "<div class=\"ticketgui\">";
include("app/views/scripts/ticket_editor.phtml"); 
echo "</div>";
?>
<script>
$(function() {
    $(".description").focus(expand_description);
});
</script>

<?php echo $this->render("pagefooter.phtml", true);?>
</div><!--container-fluid-->
<?php echo $this->render("bootfooter.phtml", true);?>

