<?include("app/views/scripts/header.phtml");?>
<div class="bread"><a href="<?=base()?>">Home</a> &gt; All Open Tickets</div>
<h2>Open Tickets</h2>

<?
foreach($this->tickets as $dest=>$tickets)
{
    echo "<h3>$dest</h3>";
    foreach($tickets as $ticket) {
        $id = $ticket->mrid;
        $title = $ticket->mrtitle;
        $url = base()."/viewer?id=$id";
        $status = Footprint::parse($ticket->mrstatus);

        echo "<p><a href='$url'>$id</a>$title ($status)<p>";
    }
}
?>

<?include("app/views/scripts/footer.phtml");?>


