<?include("app/views/scripts/header.phtml");?>
<?
            function showteam($team, $members, $already_selected) {
                echo "<h4>$team</h4>";

                $possible_values = array();
                $aka_model = new AKA();
                foreach($members as $a) {
                    $aka = $aka_model->lookupName($a);
                    $possible_values[$a] = $aka;
                }
                echo "<p>";
                echo listSelector("assignees", $possible_values, $already_selected);
                echo "</p>";
            }
?>
<script type="text/javascript" src="<?=base()?>/lib/jquery-1.3.2/plugins/jquery.textarearesizer.js"></script>
<style type="text/css">
        div.grippie {
                background:#EEEEEE url(<?=base()?>/images/grippie.png) no-repeat scroll center 2px;
                border-color:#DDDDDD;
                border-style:solid;
                border-width:0pt 1px 1px;
                cursor:s-resize;
                height:9px;
                overflow:hidden;
        }
        .resizable-textarea textarea {
                display:block;
                margin-bottom:0pt;
                width:95%;
                height: 20%;
        }
</style>

<div class="bread">You are here &gt; <a href="<?=base()?>/navigator"><?=submenutitle($this->submenu_selected)?></a> &gt; <?=$this->ticket_id?></div>
<?
if($this->ticket_type == "Security") {
    echo "<p class=\"errors\">This is a security ticket that only authorized persons can view. Please do NOT forward the contents of this ticket to any one without the OSG security team's consent</p>";
} else if($this->ticket_type == "Security_Notification") {
    echo "<p class=\"errors\">This is a security notification ticket which is only accecible for registered OIM users. Please do not forward the content of this ticket to anyone.</p>";
}

?>

<script type="text/javascript">
function gotoedit()
{
    $("#editbutton").attr("disabled", "disabled");
    $("#editbutton").val("Loading...");
    $("#information_table").load("<?=fullbase()?>/viewer/edit?id=<?=$this->ticket_id?>");
}
</script>

<?if($this->editable) {?>
    <form action="<?=fullbase()?>/viewer/update" method="post">
    <input type="hidden" name="id" value="<?=$this->ticket_id?>">

    <b>Title:</b> <input type="text" size="100" name="title" value="<?=$this->title?>"/>

    <table class="ticket_detail">
        <tr>
            <td colspan="4"><h3>Submitter</h3></td>
        </tr>
        <tr>
            <td class="header">First Name:</td><td><input type="text" value="<?=$this->submitter_fname?>" name="submitter_fname"></td>
            <td class="header">Last Name:</td><td><input type="text" value="<?=$this->submitter_lname?>" name="submitter_lname"></td>
        </tr>
        <tr>
            <?
            echo "<td class=\"header\">Email:</td><td><input type=\"text\" value=\"".$this->submitter_email."\" name=\"submitter_email\"></td>";
            ?>
            <td class="header">Phone:</td><td><input type="text" value="<?=$this->submitter_phone?>" name="submitter_phone"></td>
        </tr>
        <tr>
        <?
        ?>

        <tr>
            <td colspan="4"><h3>Routing Information</h3></td>
        </tr>
        <tr>
            <td class="header">Originating VO:</td><td>
            <select name="submitter_vo">
            <?
            foreach($this->originating_vos as $id=>$vo) {
                $selected = "";
                if($vo == $this->submitter_vo) $selected = "selected=selected";
                echo "<option id=\"$id\" $selected>$vo</option>";
            }
            ?>
            </select>
            </td>
            <?
            echo "<td class=\"header\">Originating Ticket ID</td><td><input type=\"text\" value=\"".$this->originating_ticket_id."\" name=\"originating_ticket_id\"></td>";
            ?>
        </tr>
        <tr>
            <td class="header">Destination VO:</td><td>
            <select name="destination_vo">
            <?
            foreach($this->destination_vos as $id=>$vo) {
                $selected = "";
                if($vo == $this->destination_vo) $selected = "selected=selected";
                echo "<option id=\"$id\" $selected>$vo</option>";
            }
            ?>
            </select>
            </td>
            <td class="header">Destination Ticket ID</td><td><input type="text" value="<?=$this->destination_ticket_id?>" name="destination_ticket_id"></td>

        </tr>

        <tr>
            <td colspan="4"><h3>Ticket Detail</h3></td>
        </tr>
        <tr>
            <td class="header">Ticket Type:</td><td>
            <select name="ticket_type">
            <?
            $ttype = Footprint::GetTicketTypes();
            foreach($ttype as $type) {
                $selected = "";
                if($type == $this->ticket_type) $selected = "selected=selected";
                echo "<option id=\"$type\" $selected>$type</option>";
            }
            ?>
            </select>
            </td>


            <td rowspan="6" colspan="2"><span class="header">Assignees</span><br/>
            <table width="100%"><tr>
            <?
            echo "<td valign='top'>";
            foreach(config()->editor_team_lists[0] as $team) {
                showteam($team, $this->teams[$team], $this->assignees[$team]);
            }
            echo "</td>";

            echo "<td valign='top'>";
            foreach(config()->editor_team_lists[1] as $team) {
                showteam($team, $this->teams[$team], $this->assignees[$team]);
            }
            echo "</td>";

            echo "<td valign='top'>";
            foreach(config()->editor_team_lists[2] as $team) {
                showteam($team, $this->teams[$team], $this->assignees[$team]);
            }
            echo "</td>";

            ?>
            </tr></table>

            </td>
        </tr>

        <tr>
            <td class="header">Priority:</td><td>
            <select name="priority">
            <?
            $plist = Footprint::GetPriorityList();
            foreach($plist as $id=>$p) {
                $selected = "";
                if($p == $this->priority) $selected = "selected=selected";
                echo "<option id=\"$id\" value=\"$id\" $selected>$p</option>";
            }
            ?>
            </select>

            </td>

        </tr>

        <tr>
            <td class="header">Status:</td><td>
            <?
            $style = status2style($this->status);
            //echo "<span id='status_flag' class='ticketid $style'>&nbsp;</span>";
            //echo "<select name=\"status\" onchange=\"changeflag($(this));\">";
            echo "<select name=\"status\">";
            foreach(Footprint::GetStatusList() as $status) {
                $selected = "";
                if($status == $this->status) $selected = "selected=selected";
                $style = status2style($status);
                echo "<option value=\"$status\" $selected class='ticketid $style'>$status</option>";
            }
            echo "</select>";
            ?>
            </td>
        </tr>

        <tr>
            <td class="header">Next Action Deadline:</td><td> Morning of <input type="text" name="nad" value="<?=$this->nad?>"/> </td>
        </tr>

        <tr>
            <td class="header">Next Action Item:</td><td><input type="text" name="next_action" value="<?=$this->next_action?>"/> </td>
        </tr>

        <tr>
            <td class="header">CC:</td> <td>
            <div class="ccarea">
            <?
                foreach($this->cc as $cc) {
                    echo "<div class=\"cc\"><input type=\"text\" class=\"cc\" name=\"cc[]\" value=\"$cc\" size=\"35\"/><a href=\"#\" onclick=\"$(this).parents('div.cc').remove();return false;\"><img src=\"".fullbase()."/images/delete.png\"/></a></div>";
                }
            ?>
            </div>
            <script type="text/javascript">
            function addcc(node)
            {
                var template = "<div class=\"cc\"><input type=\"text\" class=\"cc\" name=\"cc[]\" size=\"35\"/><a href=\"#\" onclick=\"$(this).parents('div.cc').remove();return false;\"><img src=\"<?=fullbase()?>/images/delete.png\"/></a></div>";
                node.append(template);
                setup_cc();
            }
            <?
            $model = new Person();
            $persons = $model->fetchAll();
            $persons_json = "";
            foreach($persons as $person) 
            {
                $name = trim($person->name);
                $email = trim($person->primary_email);
                if($name == "") $name = $email;
                if($persons_json != "") $persons_json .= ",\n";
                $persons_json .= "{ name: \"$name\", email: \"$email\"}";
            }
            ?>
            var persons = [
                <?=$persons_json?>
            ];
            $(document).ready(function() {
                setup_cc();
            });
            function setup_cc()
            {
                $(".cc").autocomplete(persons, {
                    mustMatch: false,
                    matchContains: true,
                    width: 500,
                    formatItem: function(row, i, max) {
                        return row.name + "<br/>Email: " + row.email;
                    },
                    formatMatch: function(row, i, max) {
                        return row.name + " " + row.email;
                    },
                    formatResult: function(row) {
                        return row.email;
                    }
                });
            }

            </script>
            <a class="button" href="#" onclick="addcc($(this).siblings('div.ccarea'));return false;">Add New CC</a>
            </td>
        </tr>

        <tr>
            <td class="header">Description:</td><td colspan="3">
            <select name="quickdesc" onchange="
                $('.resizable').val('Loading...');
                $.ajax({
                    url: '<?=fullbase()?>/viewer/quickdesc?id='+escape($(this).val()),
                    success: function(data) {
                        $('.resizable').val(data);
                    }
                });
                ">  
            <?
            $model = new Schema();
            $descs = $model->getquickdesc();
            echo "<option>(Quick Description)</option>";
            foreach($descs as $name=>$desc) {
                echo "<option id=\"$name\">$name</option>";
            }
            ?>
            </select>
            <textarea class="resizable" style="width: 98%" rows="5" name="description" onkeypress="checkTab(event);"></textarea>
            </td>
        </tr>
        <tr>
            <td></td>
            <td class="header" colspan="3">
                <input type="submit" value="&nbsp;&nbsp;&nbsp;Update&nbsp;&nbsp;&nbsp;"/>
            </td>
        </tr>


    </table>
    </form>

    <script type="text/javascript" src="<?=fullbase()?>/lib/checktab.js"></script>
    <script type="text/javascript">
    $(document).ready(function() {
        $("input[name='nad']").datepicker({
            dateFormat: 'yy-mm-dd'
        });
        $('textarea.resizable').TextAreaResizer();
    });
    </script>
<?} else {?>
    <div id="information_table">
        <b><?=$this->title?></b>
        <table width="100%">
        <tr>
            <td colspan="4"><h3>Contact Information</h3></td>
        </tr>
        <tr>
            <td class="header">Full Name</td><td><?=$this->submitter_name?></td>
            <td></td><td></td>
        </tr>
        <?
            if(user()->getPersonID() !== null) {
                echo "<tr>";
                echo "<td class=\"header\">Email</td><td>".$this->submitter_email."</td>";
                echo "<td class=\"header\">Phone</td><td>".$this->submitter_phone."</td>";
                echo "</tr>";
            }
        ?>
        <tr>
            <td colspan="4"><h3>Routing Information</h3></td>
        </tr>
        <tr>
            <td class="header">Originating VO</td><td><?=$this->submitter_vo?></td>
            <td class="header">Originating Ticket ID</td><td><?=$this->originating_ticket_id?></td>
        </tr>
        <tr>
            <td class="header">Destination VO</td><td><?=$this->destination_vo?></td>
            <td class="header">Destination Ticket ID</td><td><?=$this->destination_ticket_id?></td>
        </tr>

        <tr>
            <td colspan="4"><h3>Ticket Detail</h3></td>
        </tr>
        <tr>
            <td class="header">Ticket Type</td><td><?=$this->ticket_type?></td>
            <td rowspan="6" class="header">Assignees</td><td rowspan="5">
            <?
            foreach($this->assignees as $team => $list) {
                if(count($list) == 0) continue;
                echo "<h4>$team</h4>";
                echo "<p>";
                foreach($list as $name) {
                    echo $name."<br/>";
                }
                echo "</p>";
            }
            ?>
            </td>
        </tr>
        <tr>
            <td class="header">Priority</td><td><?=$this->priority?></td>
        </tr>

        <tr>
            <td class="header">Status</td><td><?=$this->status?></td>
        </tr>

        <tr>
            <td class="header">Next Action Deadline</td><td class='<?$style = nadstyle($this->nad);if($style != "") echo "flag $style";?>'>Morning of <?=$this->nad?></td>
        </tr>

        <tr>
            <td class="header">Next Action Item</td><td><?=$this->next_action?></td>
        </tr>

        <tr>
        <?if(user()->getPersonID() !== null) { ?>
             <td class="header">CC</td><td>
                <?  foreach($this->cc as $cc) { echo $cc."<br/>"; } ?>
            </td>
        <?}?>
        </tr>

        </table>
    </div>
<?}?>
<br/>

<div id="updates" style="clear: both;">
    <h3>Updates</h3>
    <p>
        <?
        $subject = "Open Science Grid: $this->title ISSUE=$this->ticket_id PROJ=".config()->project_id;
        ?>
        <a href="mailto:<?=config()->ticket_update_address?>?subject=<?=urlencode($subject)?>">Send Update Via Email</a>
    </p>
    <?
    foreach($this->descs as $time=>$desc)
    {
        $by = $desc["by"];
        $content = $desc["content"];
        $type = $desc["type"];

        //hide meta information if user doesn't have metatag access
        if(!user()->allows("view_meta")) {
            $metapos = strpos($content, config()->metatag);
            if($metapos !== FALSE) {
                //has metainfo.. hide it
                $content = substr($content, 0, $metapos);
            }
        }

        if($time > time() - 60*60*24) {
            //show in "ago" format
            $human_time = agoCalculation($time). " ago";
        } else {
            $human_time = date(config()->date_format_full, $time);
        }

        if($type == "history") {
            echo "<div class='update_history'>";
            $out = "<pre>".Footprint::parse($content)."</pre>";
            echo outputToggle("Internal Activities ($human_time)", "Internal Activities ($human_time)", $out);
            echo "</div>";
        }
        
        if($type == "description") {
            echo "<div class='update_description'>";
            echo "<div class='header'>$human_time by <b>$by</b></div>";
            $lines_raw = split("\n", $content);
            $lines = array();
            foreach($lines_raw as $line) {
                $line = trim($line);
                if(strpos($line, "&#62;") === 0) {
                    $line = "<font color='#7F7E6F'>$line</font>";
                }
                $lines[] = $line;
            }
            $content = implode("\n", $lines);
            if(count($lines) > 15) {
                //display first 10 lines
                $i = 0;
                echo "<pre>";
                for(;$i < 10; $i++) {
                    echo $lines[$i]."\n";
                }
                echo "</pre>";
                //and toggle the rest..
                $out = "";
                $out .= "<pre>";
                for(;$i < count($lines);$i++) {
                    $out .= $lines[$i]."\n";
                }
                $out .= "</pre>\n";
                echo outputToggle("Show More", "", $out);
            } else {
                //display all at once.
                echo "<pre>$content</pre>";
            }
            echo "</div>";
        }
    }
    ?>
</div>
<?include("app/views/scripts/footer.phtml");?>
