<?include("app/views/scripts/header.phtml");?>

<link rel="prefetch" href="../images/selected_back.gif"/>
<link rel="prefetch" href="../images/pointer.png"/>

<div class="bread">You are here &gt; <a href="<?=base()?>/navigator"><?=submenutitle($this->submenu_selected)?></a> &gt; <?=$this->ticket_id?></div>
<?if($this->ticket_type == "Security") {
    echo "<p class=\"errors\">This is a security ticket that only authorized persons can view. Please do NOT forward the contents of this ticket to any one without the OSG security team's consent</p>";
} else if($this->ticket_type == "Security_Notification") {
    echo "<p class=\"errors\">This is a security notification ticket which is only accecible for registered OIM users. Please do not forward the content of this ticket to anyone.</p>";
}?>

<?if($this->editable) {?>
    <?
    $suppression_control = true;
    include("app/views/scripts/ticket_editor.phtml");?>
<?} else {?>
    <?include("app/views/scripts/ticket_viewer.phtml");?>
<?}?>

<div id="updates" style="clear: both;">
    <?
    $sort_order = "down";
    if(isset($_REQUEST["sort"])) {
        $sort_order = $_REQUEST["sort"];
    }
    $flip_url = str_replace(array("&sort=up", "&sort=down"), "", fullurl());
    if($sort_order == "down") {
        $flip_url .= "&sort=up";
        $flip_button = "images/up.png";
        krsort($this->descs, SORT_NUMERIC);
    } else {
        $flip_url .= "&sort=down";
        $flip_button = "images/down.png";
        ksort($this->descs, SORT_NUMERIC);
    }
    ?>
    <h3>Past Updates</h3>
    <p>
        <span style="float: right"><a href="<?=$flip_url?>">Reverse Sorting Order</a>&nbsp;<img align="top" src="<?=$flip_button?>"/></span>
        <?
        if(!isset($_REQUEST["expandall"])) {
            $expand_all_url = fullurl()."&expandall=true";
            echo "<a style=\"float: right; margin-right: 10px;\" href=\"$expand_all_url\">Expand All Descriptions</a>";
        }
        $subject = "Open Science Grid: $this->title ISSUE=$this->ticket_id PROJ=".config()->project_id;
        ?>
        <a href="mailto:<?=config()->ticket_update_address?>?subject=<?=rawurlencode($subject)?>">Send Update Via Email</a>
    </p>
    <?
    foreach($this->descs as $time=>$desc)
    {
        $by = $desc["by"];
        $content = $desc["content"];
        $type = $desc["type"];

        //hide meta information if user doesn't have metatag access
        if(!user()->allows("view_meta")) {
            //hide it!
            $metapos = strpos($content, config()->metatag);
            if($metapos !== FALSE) {
                //has metainfo.. hide it
                $content = substr($content, 0, $metapos);
            }
        } else {
            //show it!
            $metapos = strpos($content, config()->metatag);
            if($metapos !== FALSE) {
                //has metainfo.. let's split the ticket into 2 parts
                $meta_information = substr($content, $metapos + strlen(config()->metatag));
                $content = trim(substr($content, 0, $metapos));
            } else {
                $meta_information = null;
            }
        }

        if($time > time() - 60*60*24) {
            //show in "ago" format
            $detail = date(config()->date_format_full, $time);
            $ago = agoCalculation($time). " ago";
            $human_time = "<span onmouseover=\"$(this).text('$detail');\" onmouseout=\"$(this).text('$ago');\">$ago</span>";
        } else {
            $human_time = date(config()->date_format_full, $time);
        }


        //history == internal activities
        if($type == "history") {
            echo "<div class='update_history'>";
            $out = "<pre>".Footprint::parse($content)."</pre>";
            echo outputToggle("Footprints Activities ($human_time)", "Footprints Activities ($human_time)", $out);
            echo "</div>";
        }
        
        if($type == "description") {
            if(user()->isGuest()) {
                //mask email address
                if(preg_match('/^[^@]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$/', $by)) {
                    $by = substr($by, 0, strpos($by, "@"))."@....";
                }
            }

            $anchor = $time;
            echo "<div class='update_description'>";
            echo "<div class='header' onclick=\"document.location='#$anchor'; reset_anchor();\">";
            echo "<img style=\"padding-right: 3px;\" class=\"anchor_img\" align=\"right\" src=\"images/application_link.png\"/>";
            echo "<a name=\"$anchor\">&nbsp;</a>$human_time by <b>$by</b>";
            echo "</div>";
            $lines_raw = split("\n", $content);
            $lines = array();
            foreach($lines_raw as $line) {
                $line = trim($line);
                if(strpos($line, "&#62;") === 0) {
                    $line = "<font color='#7F7E6F'>$line</font>";
                }
                $lines[] = $line;
            }
            $content = implode("\n", $lines);
            if(!isset($_REQUEST["expandall"]) && count($lines) > config()->description_showlines) {
                $i = 0;
                echo "<pre>";
                for(;$i < config()->description_showlines; $i++) {
                    echo $lines[$i]."\n";
                }
                echo "</pre>";
                //and toggle the rest..
                $out = "";
                $out .= "<pre>";
                for(;$i < count($lines);$i++) {
                    $out .= $lines[$i]."\n";
                }
                $out .= "</pre>\n";

                echo outputToggle("Show More", "", $out);
            } else {
                //display all at once.
                echo "<pre>$content</pre>";
            }
            echo "</div>";
        }

        //meta information
        if(!empty($meta_information)) {
            echo "<div class=\"meta_information\">";
            $out = "<pre>$meta_information</pre>";
            echo outputToggle("Ticket Creation Information", "Ticket Creation Information", $out);
            echo "</div>";
        }
    }
    ?>
    <table width="100%">
    <tr><td width="33%" style="padding-right: 5px;">
        <h3>Metadata</h3>
        <div class="metadata">
        <?
        if(count($this->metadata) == 0) {
            echo "No metadata stored for this ticket.";
        }
        foreach($this->metadata as $item) {
            echo "<p><span class=\"header\">$item->key</span>&nbsp;";
            echo $item->value."</p>";
        }
        ?>
        </div>
    </td><td width="66%">
        <?
        echo "<h3>Similar Recent Tickets</h3>";
        if(isset($this->similar_tickets)) { 
            foreach($this->similar_tickets as $ticket) {
                // ["id"]=> string(3) "386" ["title"]=> string(21) "This is a test ticket" ["status"]=> string(11) "Engineering" ["dest"]=> string(3) "MIS" ["url"]=> string(50) "https://localhost.localdomain/ticket/viewer?id=386" ["desc"]=> string(43) "[by Soichi Hayashi] This is a test ticket " ["score"]=> string(3) "100" } 
                echo "<a href=\"".fullbase()."/viewer?id=".$ticket->id."\"><b>".$ticket->id."</b> ".$ticket->title." (".$ticket->status.")</a><p>".$ticket->desc."</p>";
            }
        } else {
            echo "No similar tickets found that are modified within the last 30 days.";
        }

/*
        <div id="custom_search_area">
            <a href="javascript:void(0);" onclick="return load_similar_tickets();">Search</a>
        </div>
        <script type="text/javascript">
        function load_similar_tickets() {
            $("#custom_search_area").html("<p class='loading'>Loading...</p>");
            $.getScript("https://www.googleapis.com/customsearch/v1?key=<?=config()->google_search_api_key?>&cx=<?=config()->google_custom_search?>&q=ldap&callback=hndlr");
        }
        function hndlr(response) {
            console.dir(response);
            var e = document.getElementById("custom_search_area");-
            e.innerHTML = "";
            for (var i = 0; i < response.items.length; i++) {
                var item = response.items[i];
                e.innerHTML += "<a href=\""+item.link+"\">" + (item.htmlTitle) + "</a><br>";
                e.innerHTML += "<p>" + (item.htmlSnippet) + "</p>";
            }
        }

*/
        ?>
    </td></tr></table>

</div>
<script type="text/javascript">
function reset_anchor() {
    $("#updates .selected").removeClass("selected");

    var urls = document.location.toString().split('#'); 
    var anchor = urls[1];
    if(anchor) {
        $("a[name='"+anchor+"']").parents(".update_description").addClass("selected");
    }
}
$(document).ready(function() {
    reset_anchor();
    var ADDITIONAL_COOKIE_NAME = 'gocticket';
    var options = { path: '/', expires: 365};
    v = $.cookie("closewindow");
    if(!v) {
        //default
        $("#closewindow").attr("checked", "", options);
    } else {
        if(v == "true") {
            $("#closewindow").attr("checked", "checked", options);
        } else {
            $("#closewindow").attr("checked", "", options);
        }
    }

    $("#closewindow").click(function() {
        $.cookie("closewindow", $(this).attr('checked'), options);
    });
});
</script>
<?include("app/views/scripts/footer.phtml");?>
