<?include("app/views/scripts/header.phtml");?>
<div class="bread"><a href="<?=base()?>">Home</a> &gt; Ticket Viewer</div>
Permission Denied to view ticket id <?=$this->ticketid?>: Security Issue tickets can only be viewed on this website if you have loaded your X509 certificate on your web browser, and are registered on OIM with that certificate.
</div>
<?include("app/views/scripts/footer.phtml");?>
