<?php echo $this->render("bootheader.phtml", true);?>
<p>Permission Denied to view ticket id <?=$this->ticket_id?></p>
<p>This is a Security Announcement ticket. It can only be viewed on this website if you have loaded your X509 certificate on your web browser, and are registered on OIM with that certificate.</p>
<?php echo $this->render("pagefooter.phtml", true);?>
</div><!--container-fluid-->
<?php echo $this->render("bootfooter.phtml", true);?>
