<?include("app/views/scripts/header.phtml");?>
<div class="bread">You are here &gt; View Tickets</div>

<style type="text/css">
<?include("app/views/scripts/tab11.css");?>
</style>

<div class="tabarea">
<div id="tabs11">
<ul>
                <!-- CSS Tabs -->
<li><a href="<?=fullbase()?>/opentickets"><span>Open Tickets</span></a></li>
<li id="current"><a href="#"><span>Closed Tickets</span></a></li>

        </ul>
</div>
<div class="tabcontent">
<br/>
<?
foreach($this->tickets as $dest=>$tickets)
{
    echo "<h3>$dest</h3>";
    foreach($tickets as $ticket) {
        $id = $ticket->mrid;
        $title = $ticket->mrtitle;
        $url = base()."/viewer?id=$id";
        $status = Footprint::parse($ticket->mrstatus);

        echo "<p><a href='$url'>$id</a>$title ($status)<p>";
    }
}
?>
</div>
</div>

<?include("app/views/scripts/footer.phtml");?>


