<?include("app/views/scripts/header.phtml");?>
<div class="bread">You are here &gt; <?=submenutitle($this->submenu_selected)?></div>
<ul class="subsection_tabs">
    <li class="tab"><a href="<?=fullbase()?>/opentickets"><span>Open Tickets</span></a></li>
    <li class="tab"><a class="active" href="#"><span>Closed Tickets</span></a></li>
</ul>
<div class="tabcontent">
<?
foreach($this->tickets as $dest=>$tickets)
{
    echo "<h3>$dest</h3>";
    foreach($tickets as $ticket) {
        $id = $ticket->mrid;
        $title = $ticket->mrtitle;
        $url = base()."/viewer?id=$id";
        $status = Footprint::parse($ticket->mrstatus);

        echo "<p><a href='$url'>$id</a>$title ($status)<p>";
    }
}
?>
</div>
<?include("app/views/scripts/footer.phtml");?>


