<?include("app/views/scripts/header.phtml");?>

<div class="bread">You are here &gt; <?=submenutitle($this->submenu_selected)?></div>

<script type="text/javascript">
$(document).ready(function() {
    $('#tabs').tabs({
        select: function(event, ui) {
            location.href = "<?=fullbase()?>/navigator/"+ui.tab.id;
            return false;
        }
    });
    $('#tabs li').removeClass("ui-tabs-selected");
    $('#tabs li').removeClass("ui-state-active");
    //select current tab
    $($('#tabs a[id=<?=$this->activetab?>]').parents()[0]).addClass("ui-tabs-selected").addClass("ui-state-active");
});
</script>

<div id="tabs">
  <ul class="tabNavigation">
    <li><a id="open" href="#open_ref">Opened Ticket by Destination VO</a></li>
    <li><a id="openassign" href="#openassign_ref">Opened Tickets by GOC Assignee</a></li>
    <li><a id="close" href="#close_ref">Closed Ticket within Last 90 Days</a></li>
  </ul>
    <div style="padding: 10px;">
    <table width="100%">
    <tr><th>ID</th><th>Title</th><th>Status</th><th width="150">Update Time</th></tr>
    <?
    foreach($this->tickets as $dest=>$tickets)
    {
        if(trim($dest) == "") $dest = "(N/A)";
        echo "<tr><td colspan=4><h3>$dest</h3></td></tr>";
        foreach($tickets as $ticket) {
            $id = $ticket->mrid;
            $title = $ticket->mrtitle;
            $url = base()."/viewer?id=$id";
            $status = Footprint::parse($ticket->mrstatus);
            $style = status2style($status);
            $status = str_replace(" ", "&nbsp;", $status);
            $moddate = $ticket->mrupdatedate;

            echo "<tr onclick=\"window.open('$url','_blank');\">";
            echo "<th>$id&nbsp;&nbsp;</th>";
            echo "<td>$title</td>";
            echo "<td><span class='ticketid $style'>$status&nbsp;&nbsp;</span></td>";
            echo "<td>$moddate</td>";
            echo "</tr>";
        }
    }
    ?>
    </table>
    </div>
</div>


<?include("app/views/scripts/footer.phtml");?>


