<?include("app/views/scripts/header.phtml");?>

<link rel="stylesheet" type="text/css" href="<?=fullbase()?>/lib/jquery.datatables-1.7.0/css/demo_table_jui.css" />
<script type="text/javascript" src="<?=fullbase()?>/lib/jquery.datatables-1.7.0/js/jquery.dataTables.min.js"></script>

<meta http-equiv="refresh" content="<?=config()->navigator_refresh?>"/>

<style>
.column_buttons,
.opened_toolbar,
.closed_toolbar {
display: inline-block;
}

.column_buttons,
.column_buttons button { 
padding: 2px;
}
.column_buttons button:hover {
cursor: pointer;
}
.column_buttons .ui-state-default {
color: #ccc;
}
.column_buttons .ui-state-active {
color: #000;
}

span.ui-icon_disable {
display: inline !important;
}
input.search {
margin: 0px;
}
th {
padding: 3px;
}
#content {
display: none;
}
</style>

<script type="text/javascript">
<?
    $columns = array(
        array("name"=>"ID", "type"=>"numeric"), 
        array("name"=>"Submit Date", "type"=>"date"),
        array("name"=>"Title", "type"=>"html"), 
        array("name"=>"Update Date", "type"=>"date"), 
        array("name"=>"Next Action", "type"=>"string"), 
        array("name"=>"NAD", "type"=>"html"), 
        array("name"=>"Priority", "type"=>"html"), 
        array("name"=>"Assignees", "type"=>"string"), 
        array("name"=>"CCs", "type"=>"string"), 
        array("name"=>"Origin.&nbsp;VO", "type"=>"string"), 
        array("name"=>"Dest.&nbsp;VO", "type"=>"string")
        );
    $column_types = "";
    foreach($columns as $id=>$column) {
        if($column_types != "") {
            $column_types .= ", ";
        }
        $column_types .= "{ \"sType\": \"".$column["type"]."\"}";
    }

?>
</script>
<?

echo "You are here > View Tickets (use <a href=\"".fullbase()."/navigatorold\">Old View</a>)";

echo "<h3>Open Tickets</h3>";
$search = $this->table_search["opened"];
showtickets($this->assigned_tickets, "opened", $columns, $search);

echo "<h3>Closed within ".$this->closed_days." days</h3>";
$search = $this->table_search["closed"];
showtickets($this->closed_tickets, "closed", $columns, $search);

function showtickets($tickets, $id, $columns, $search) {
?>
    <table cellpadding="0" cellspacing="0" border="0" class="display" id="<?=$id?>">
    <thead>
        <tr>
        <?
        foreach($columns as $cid=>$column) {
            echo "<th>".str_replace(" ", "&nbsp;", $column["name"]);
            //I have to include search field inside column header so that DataTable will hide it correctly
            $search_value = "";
            if(isset($search[$cid][0])) {
                $search_value = $search[$cid][0];
            }
            echo "<br/>";
            echo "<input pos=\"$cid\" onkeyup=\"".$id."_table.fnFilter(this.value, $(this).attr('pos'));\" value=\"$search_value\" type=\"text\" class=\"search\" style=\"width: 88%;\" onclick=\"event.cancelBubble = true;\"/>";
            echo "</th>";
        }?>
        </tr>
    </thead>
    <?
    $model = new Schema();
    $teams = $model->getteams();
    $aka_model = new AKA();

    foreach($tickets as $ticket) {
        if($ticket->tickettype == "Security") {
            if(user()->isguest()) {
                //don't show security ticket to guest user 
                continue;
            } 
        }

        $url = base()."/viewer?id=".$ticket->mrid;
        $target = "ticket_".$ticket->mrid;

        //assignee, cc
        $assignees = array();
        $ccs = array();
        foreach(explode(" ", $ticket->mrassignees) as $a) {
            //FP somehow put CCs on assginee field...-
            if(strlen($a) >= 3 and strpos($a, "CC:") === 0) {
                $ccs[] = substr($a, 3);
                continue;
            }
            //FP somehow contains team names on assignee... ignore it
            $team_name = false;
            foreach($teams as $team) {
                if($team->team == $a) {
                    $team_name = true;
                    break;
                }
            }
            if($team_name) continue;

            //store to assignee list
            $aka = $aka_model->lookupName($a);
            $assignees[$a] = str_replace(" ", "&nbsp;", $aka);
        }

        //priority
        $priority = Footprint::getPriority($ticket->mrpriority);
        switch($ticket->mrpriority) {
        case 3: $priority = "<font color='#c90'>$priority</font>"; break;
        case 2: $priority = "<font color='red'>$priority</font>"; break;
        case 1: $priority = "<font color='red'>$priority</font>"; break;
        }

        //nad
        $nad_unix = strtotime($ticket->nad);
        $nad = date("Y-m-d", $nad_unix);
        if($nad_unix < time()) {
            $nad = "<font color='red'>$nad</font>";
        } else if($nad < time() + 3600*config()->nad_alert_hours) {
            $nad = "<font color='#c90'>$nad</font>";
        }

        //dates
        //for some reason, datatable doesn't sort the date correctly if there is timestamp on it.. just show date
        $submit_date = substr($ticket->mrsubmitdate, 0, 10);
        $update_date = substr($ticket->mrupdatedate, 0, 10);

        //ticket type
        $title = $ticket->mrtitle;
        if($ticket->tickettype == "Security") {
            $title = "<span class='red tag'>Security</span>$title";
        }

        ?>
        <tr onclick="window.open('<?=$url?>','<?=$target?>');">
            <td><?=$ticket->mrid?></td>
            <td><?=$submit_date?></td>
            <td><?=$title?></td>
            <td><?=$update_date?></td>
            <td><?=$ticket->nextaction?></td>
            <td><?=$nad?></td>
            <td><?=$priority?></td>
            <td><?=implode("<br>", $assignees)?></td>
        <?
            if(!user()->isguest()) {
                echo "<td>".implode("<br>", $ccs)."</td>";
            } else {
                echo "<td>(Only Visible for OIM users)</td>";
            }
        ?>
            <td><?=$ticket->mrorigin?></td>
            <td><?=$ticket->mrdest?></td>
        </tr>
        <?
    }
    ?>  
    </table>
<?
}
?>

<script type="text/javascript">
<?
$columns = array(
    array("name"=>"ID", "type"=>"numeric"), 
    array("name"=>"Submit Date", "type"=>"date"),
    array("name"=>"Title", "type"=>"html"), 
    array("name"=>"Update Date", "type"=>"date"), 
    array("name"=>"Next Action", "type"=>"string"), 
    array("name"=>"NAD", "type"=>"html"), 
    array("name"=>"Priority", "type"=>"html"), 
    array("name"=>"Assignees", "type"=>"string"), 
    array("name"=>"CCs", "type"=>"string"), 
    array("name"=>"Origin.&nbsp;VO", "type"=>"string"), 
    array("name"=>"Dest.&nbsp;VO", "type"=>"string")
    );
$column_types = "";
foreach($columns as $id=>$column) {
    if($column_types != "") {
        $column_types .= ", ";
    }
    $column_types .= "{ \"sType\": \"".$column["type"]."\"}";
}
?>
var opened_table;
var closed_table;

$(document).ready(function() {

     opened_table = $('#opened').dataTable({
        "bJQueryUI": true,
        "bAutoWidth": false,
        "bPaginate": false,
        "bStateSave": true,
        "bInfo": false,
        "iCookieDuration": 60*60*24*90, /*90 days*/
        "sDom": '<"opened_toolbar">frtip',
        "aoColumns": [ <?=$column_types?> ]
    });
    closed_table = $('#closed').dataTable({
        "bJQueryUI": true,
        "bAutoWidth": false,
        "bPaginate": false,
        "bStateSave": true,
        "bInfo": false,
        "iCookieDuration": 60*60*24*90, /*90 days*/
        "sDom": '<"closed_toolbar">frtip',
        "aoColumns": [ <?=$column_types?> ]
    });

    $("div.opened_toolbar").html('<?

    echo "<div class=\"column_buttons\"> Show Columns: ";
    $first = true;
    foreach($columns as $id=>$column) {
        $name = $column["name"];
        $active = "ui-state-active";
        if(isset($this->opened_table_cols[$id]) && $this->opened_table_cols[$id] == false) {
            $active = "";
        }
        if($first) {
            $first = false;
            $active .= " ui-corner-left";
        }
        if($name == $columns[sizeof($columns)-1]["name"]) {
            $active .= " ui-corner-right";
        }
        echo "<button class=\"ui-state-default $active\" onclick=\"fnShowHideOpened(this, $id);\">$name</button>";
    }
    echo "</div>";
    ?>');

    $("div.closed_toolbar").html('<?
    echo "<div class=\"column_buttons\"> Show Columns: ";
    $first = true;
    foreach($columns as $id=>$column) {
        $name = $column["name"];
        $active = "ui-state-active";
        if(isset($this->closed_table_cols[$id]) && $this->closed_table_cols[$id] == false) {
            $active = "";
        }
        if($first) {
            $first = false;
            $active .= " ui-corner-left";
        }
        if($name == $columns[sizeof($columns)-1]["name"]) {
            $active .= " ui-corner-right";
        }
        echo "<button class=\"ui-state-default $active\" onclick=\"fnShowHideClosed(this, $id);\">$name</button>";
    }
    echo "</div>";
    ?>');

    $("#content").show();
});

function fnShowHideOpened(button, iCol )
{
    if($(button).hasClass("ui-state-active")) {
        $(button).removeClass("ui-state-active");
    } else {
        $(button).addClass("ui-state-active");
    }

    var bVis = opened_table.fnSettings().aoColumns[iCol].bVisible;
    opened_table.fnSetColumnVis( iCol, bVis ? false : true );
}

function fnShowHideClosed(button, iCol )
{
    if($(button).hasClass("ui-state-active")) {
        $(button).removeClass("ui-state-active");
    } else {
        $(button).addClass("ui-state-active");
    }
    var bVis = closed_table.fnSettings().aoColumns[iCol].bVisible;
    closed_table.fnSetColumnVis( iCol, bVis ? false : true );
}

</script>

<?include("app/views/scripts/footer.phtml");?>
