<blockquote>
<h4>What does <b>CRITICAL</b> mean?</h4>
    <br/>
    <div class="indent">
        <ul>
        <li>A problem or issue which needs immediate, undivided attention from GOC staff until resolved.</li>
        <li>The submitter is expected to be available immediately for contact by GOC staff for details regarding the reported problem.</li>
        <li>Problems that are not related to an immediate security threat or a GOC critical service outage will be handled during normal business hours.</li>
        </ul>
    </div>
</blockquote>

