<form action="<?=$this->escape($this->element->getAction())?>"
      method="<?=$this->escape($this->element->getMethod())?>"
      name="myform">
<dl>

<dd>
<?=$this->render("yourinfo.phtml", true)?>
</dd>

<dd> 
    <h3>Issue Detail</h3>
    <p> Now tell us about the issue.  </p>
</dd>

<?=$this->element->resource_type?>
</dl>

<dl id="resource_id_with_issue_1_holder" class="hidden">
<?=$this->element->resource_id_with_issue_1?>
</dl>
<dl id="resource_id_with_issue_2_holder" class="hidden">
<?=$this->element->resource_id_with_issue_2?>
</dl>
<dl id="type_holder" class="hidden">
    <dt><label for="type">Affected Service</dt>
    <dd id="type">
    </dd>
</dl>
<dl id="title_holder" class="hidden">
<?=$this->element->title?>
</dl>

<dl>
<?=$this->element->admin?>
<?=$this->element->detail?>

<?=$this->element->submit_button?>
</dl>
</form>

<script type="text/javascript">
function show_resourcelist() {
    $("#resource_id_with_issue_1_holder").hide();
    $("#resource_id_with_issue_2_holder").hide();
    //find currently selected item
    var grid_type = $("#resource_type").val();
    $("#resource_id_with_issue_"+grid_type+"_holder").show();
    var rid = $("#resource_id_with_issue_"+grid_type).val();
    if(rid) {
        loadServiceType(rid);
    }
}
function setTitleAndType() 
{
    id = this.selectedIndex;
    if(!id) {
        $("#title_holder").hide();
        $("#type_holder").hide();
    } else {
        var rname = this.options[id].text;
        $("#title").attr("value", "Resource Specific Issue on "+rname);
        $("#title_holder").show();
        loadServiceType(this.options[id].value);
    }
}
function loadServiceType(rid)
{
    $("#type").load("<?=fullbase()?>/resource/loadtype?rid="+rid, function() {
        $("#title_holder").show();
        $("#type_holder").show();
    });
}

show_resourcelist();
$("#resource_type").change(function() {
    show_resourcelist();
});
$("#resource_id_with_issue_1").change(setTitleAndType);
$("#resource_id_with_issue_2").change(setTitleAndType);
</script>
