<?include("app/views/scripts/header.phtml");?>
<div class="bread"><a href="<?=base()?>">Home</a> &gt; An issue on specific OSG resource</div>
<h2>Ticket Request Form</h2>
<div class="form">
<?
if($this->errors != "") {
    echo "<p class='errors'>".$this->errors."</p>";
}
?>
<?=$this->form?>
</div>
<?include("app/views/scripts/footer.phtml");?>

<script type="text/javascript">
function show_resourcelist() {
    $("#resource_id_with_issue_1").hide();
    $("#resource_id_with_issue_2").hide();
    //find currently selected item
    var grid_type = $("#resource_type").val();
    $("#resource_id_with_issue_"+grid_type).show();
}
show_resourcelist();
$("#resource_type").change(function() {
    show_resourcelist();
});
</script>
