<?include("app/views/scripts/header.phtml");?>
<p class="errors">This form is deprecated. Please use Bulk resource submitter instead.</p>
<div class="bread">You are here &gt; <a href="<?=base()?>/open"><?=submenutitle($this->submenu_selected)?></a> &gt; RSV related trouble ticket</div>
<div class="form">
<?
if($this->errors != "") {
    echo "<p class='errors'>".$this->errors."</p>";
}
?>
<?=$this->form?>
</div>
<?include("app/views/scripts/footer.phtml");?>


