<style>
input[type=text],
select {
width: 100%;
}
textarea {
width: 100%;
height: 80px;
}
.ccarea {
width: 48%;
}

</style>

<form action="<?=$this->escape($this->element->getAction())?>"
      method="<?=$this->escape($this->element->getMethod())?>" name="submit_form">

<p>Thanks for your interest in the OSG's Campus Researchers Club - a program to partner individual researchers who have Distributed High Throughput Computing (DHTC) needs with an OSG member site. Once partnered with a member site, your sponsor will help you get your application running in a DHTC environment.</p>
<p>This program is not intended to be a long term solution to your research computing needs, but rather a production worthy proof of concept. Once validated, we can help you implement a DHTC solution at your institution to meet your longer-term goals.</p>

<legend>Contact Information</legend>
<p class="help-block">We use this information to contact you</p>
<?=$this->render("yourinfo.phtml", true)?>

<legend>Research Details</legend>
<p class="help-block">Tell us a little about your research</p>
<?=$this->element->institution?>
<?=$this->element->department?>

<label>Your Preferred Sponsor</label>
<select name="sponsor">
<option>I don't have a preference</option>
<option>Center for High Throughput Computing at UW-Madison</option>
<option>High Throughput Center at UCSD</option>
<option>Holland Computing Center at UN-Lincoln</option>
</select>

<label>Please provide a brief description of your research to help us answer the question "What kind of research does the OSG help with?"</label>
<textarea name="desc"></textarea>

<label>Why do you think DHTC is a good solution for advancing your research?</label>
<textarea name="fit"></textarea>

How did you hear about us? If someone referred you to us, please let us know whom.<br>
<textarea name="heard"></textarea>

Do you have any immediate questions or other comments?<br>
<textarea name="comments"></textarea>

We'd like to schedule an initial call to better understand your needs and determine next steps. What would be a good time to contact you?<br>
<textarea name="call"></textarea>


<?php if(user()->isguest()) { ?>
    <?=$this->element->recaptcha?>
<?php } else {?>
    <label>CC</label>
    <div class="ccarea">
        <?php
        $ccs = array();
        if(Zend_Registry::isRegistered("passback_ccs")) {
            $ccs = Zend_Registry::get("passback_ccs");
        }
        include_once("app/views/cc_editor.php");
        cceditor($ccs);
        ?>
    </div>
    <a class="btn btn-small" href="#" onclick="addcc($(this).siblings('div.ccarea'));return false;"><i class="icon-plus"></i> Add CC</a> 
<?php } ?>

<div class="form-actions">
<button type="submit" name="submit_button" class="btn btn-primary btn-large" id="submit_button">Submit</button>
</div>

</form>

<script>
$(function() {
    //repopulate optional details
    <?php if(isset($_REQUEST["desc"])) {?>
        $("textarea[name='desc']").val("<?php echo addslashes($_REQUEST["desc"])?>");
    <?php } ?>
    <?php if(isset($_REQUEST["fit"])) {?>
        $("textarea[name='fit']").val("<?php echo addslashes($_REQUEST["fit"])?>");
    <?php } ?>
    <?php if(isset($_REQUEST["heard"])) {?>
        $("textarea[name='heard']").val("<?php echo addslashes($_REQUEST["heard"])?>");
    <?php } ?>
    <?php if(isset($_REQUEST["comments"])) {?>
        $("textarea[name='comments']").val("<?php echo addslashes($_REQUEST["comments"])?>");
    <?php } ?>
    <?php if(isset($_REQUEST["call"])) {?>
        $("textarea[name='call']").val("<?php echo addslashes($_REQUEST["call"])?>");
    <?php } ?>
});

</script>
