<?php


$client = new Google_Client();
$client->setAuthConfigFile('client_secrets.json');
$client->addScope("https://www.googleapis.com/auth/blogger");
$client->setRedirectUri('https://' . $_SERVER['HTTP_HOST'] . '/oauth');


if (! isset($_GET['code'])) {
	slog("code is not set, authenticating with url");
  $auth_url = $client->createAuthUrl();
 header('Location: ' . filter_var($auth_url, FILTER_SANITIZE_URL));
} else {
	slog("code is set, aunthenticating with code");
  $client->authenticate($_GET['code']);
  $_SESSION['access_token'] = $client->getAccessToken();
  $redirect_uri = 'https://' . $_SERVER['HTTP_HOST'] . '/notify';
  header('Location: ' . filter_var($redirect_uri, FILTER_SANITIZE_URL));
}

