<form action="<?=$this->escape($this->element->getAction())?>"
      method="<?=$this->escape($this->element->getMethod())?>">

<?=$this->render("yourinfo.phtml", true)?>

    <h3>Request Detail</h3>
    <?=$this->element->req_type?>
    <?=$this->element->req_id?>
    <br/>

    <?=$this->element->vo?>
    <br/>

</dl>
    <dl id="sponsor_holder">
    <?=$this->element->req_sponsor?>
    </dl>
<dl>
    <?=$this->element->req_name?>
    <?=$this->element->req_email?>
    <?=$this->element->req_phone?>
    <?=$this->element->req_dn?>
    <br/>

    <?=$this->element->submit_button?>

</form>

<script type="text/javascript">
showhide_sponsor();
function showhide_sponsor()
{
    var req_type = $("#req_type").val();
    if(req_type == "personal") {
        $("#sponsor_holder").show();
    } else {
        $("#sponsor_holder").hide();
    }
}
$("#req_type").change(function() {
    showhide_sponsor();
});
</script>
