<?php echo $this->render("bootheader.phtml", true);?>
<div class="container-fluid">
<?php echo $this->alerts();?>
<div class="page-header"><h2><?php echo $this->page_title?></h2></div>
<?=$this->form?>

<script type="text/javascript">
<?
$sponsors = "";
foreach($this->sponsors as $sponsor) 
{
    $name = trim($sponsor->name);
    $email = $sponsor->primary_email;
    if($sponsors != "") $sponsors .= ",\n";
    $sponsors .= "{ name: \"$name\", to: \"$email\"}";
}
?>
var sponsors = [
    <?=$sponsors?>
];

$(document).ready(function() {
    $("#req_sponsor").autocomplete(sponsors, {
        mustMatch: true,
        matchContains: true,
        width: 500,
        formatItem: function(row, i, max) {
            return row.name + "<br/>Email: " + row.to;
        },
        formatMatch: function(row, i, max) {
            return row.name + " " + row.to;
        },
        formatResult: function(row) {
            return row.name;
        }
    });
});
</script>

<?php echo $this->render("pagefooter.phtml", true);?>
</div><!--container-fluid-->
<?php echo $this->render("bootfooter.phtml", true);?>

