<?include("app/views/scripts/header.phtml");?>
<script type="text/javascript" src="<?=base()?>/lib/jquery.autocomplete.min.js"></script>
<link rel="stylesheet" type="text/css" href="<?=base()?>/css/jquery.autocomplete.css" />

<div class="bread">You are here &gt; <a href="<?=base()?>/open">Open A Ticket</a> &gt; Send Certificate Request Email</div>
<h2>Send Certificate Request Email</h2>
<div class="form">
<?
if($this->errors != "") {
    echo "<p class='errors'>".$this->errors."</p>";
}
?>
<?=$this->form?>
</div>
<script type="text/javascript">
<?
$sponsors = "";
foreach($this->sponsors as $sponsor) 
{
    $name = trim($sponsor->first_name. " ".$sponsor->last_name);
    $email = $sponsor->primary_email;
    if($sponsors != "") $sponsors .= ",\n";
    $sponsors .= "{ name: \"$name\", to: \"$email\"}";
}
?>
var sponsors = [
    <?=$sponsors?>
];

$(document).ready(function() {
    $("#req_sponsor").autocomplete(sponsors, {
        mustMatch: true,
        matchContains: true,
        width: 500,
        formatItem: function(row, i, max) {
            return row.name + "<br/>Email: " + row.to;
        },
        formatMatch: function(row, i, max) {
            return row.name + " " + row.to;
        },
        formatResult: function(row) {
            return row.name;
        }
    });
});
</script>
<?include("app/views/scripts/footer.phtml");?>
