<?php
require "/usr/local/ticket/vendor/autoload.php";

$client_id = config()->cilogon_client_id;
elog("current host:". $_SERVER['HTTP_HOST']);

if(preg_match("/\bopensciencegrid\b/i",$_SERVER['HTTP_HOST'])){
  $redirect_url=config()->cilogon_client_redirect;
  elog("redirect: opensciencegrid");
}else{
  $redirect_url=config()->cilogon_client_redirect_grid;
  elog("redirect: grid.iu.edu");
}
elog("callback url:". $redirect_url);

$redirect_url=config()->cilogon_client_redirect;                                                                                                                                        

$client_host=config()->cilogon_client_host;
$client_secret=config()->cilogon_client_secret;

$oidc = new OpenIDConnectClient($client_host,                                                                            
				$client_id,                                 
				$client_secret);       

$oidc->setRedirectURL($redirect_url);
$oidc->addScope("openid");                                                                                                                                        
$oidc->addScope("email");                                                                                                                                         
$oidc->addScope("profile");                                                                                                                                       
$oidc->addScope("org.cilogon.userinfo");                                                                                                                          
$oidc->authenticate();                                                                                                                                            
$name = $oidc->requestUserInfo('email');                                                                                                                        


if($_SESSION['access_token_sso']==""){                                                                                                                             
    
if (isset($_REQUEST['code'])) {                                                                                                                                   
  $_SESSION['access_token_sso'] = $oidc->getAccessToken();                                                                                                            
  $_SESSION['email'] = $oidc->requestUserInfo('email');                                                                                                     
  $_SESSION['family_name'] = $oidc->requestUserInfo('family_name');                                                                                               
  $_SESSION['given_name'] = $oidc->requestUserInfo('given_name');                                                                                                 
  $_SESSION['idp'] = $oidc->requestUserInfo('idp');                                                                                                               
  $_SESSION['idp_name'] = $oidc->requestUserInfo('idp_name');
 
  if($_SESSION["ref_loc"]!=""){
    header("location: ".$_SESSION["ref_loc"]."/");
    
  }else{
    header("location: https://".$_SERVER['SERVER_NAME']."/");
    
  }

}                 

                                                                                                                                                
}else{                                                                                                                                                         
   if($_SESSION['email']!=""){                                                                                                                  
     
     if($_SESSION["ref_loc"]!=""){
       header("location: ".$_SESSION["ref_loc"]."/");
       
     }else{
       header("location: https://".$_SERVER['SERVER_NAME']."/");
     }
     
   }                                                                                                                                            

 }                                                    

?>
