<style>
textarea {
width: 100%;
height: 200px;
}
select, input[type=text] {
width: 100%;
}
</style>
<?
function checked($e)
{
    if($e->checked) return "checked=checked";
}
?>

<form action="<?=$this->escape($this->element->getAction())?>"
      method="<?=$this->escape($this->element->getMethod())?>">

<legend>Send To</legend>
<div class="well">
    <div class="well-title">Security Contacts</div>
    <input type="checkbox" name="goc" id="goc" value="1" disabled="disabled" checked=checked/>
    GOC &nbsp;&nbsp;&nbsp;

    <input type="hidden" name="rsecurity" value="0">
    <input type="checkbox" name="rsecurity" id="rsecurity" value="1" <?=checked($this->element->rsecurity)?>>
    Resource Security Contacts&nbsp;&nbsp;&nbsp;

    <input type="hidden" name="vsecurity" value="0">
    <input type="checkbox" name="vsecurity" id="vsecurity" value="1" <?=checked($this->element->vsecurity)?>>
    VO Security Contacts&nbsp;&nbsp;&nbsp;

    <input type="hidden" name="ssecurity" value="0">
    <input type="checkbox" name="ssecurity" id="ssecurity" value="1" <?=checked($this->element->ssecurity)?>>
    SC Security Contacts&nbsp;&nbsp;&nbsp;
</div>

<div class="well">
    <div class="well-title">Mailing Lists</div>
    <input type="hidden" name="support" value="0">
    <input type="checkbox" name="support" id="support" value="1" <?=checked($this->element->support)?>>
    Support Centers&nbsp;&nbsp;&nbsp;

    <input type="hidden" name="general" value="0">
    <input type="checkbox" name="general" id="general" value="1" <?=checked($this->element->general)?>>
    OSG-General&nbsp;&nbsp;&nbsp;

    <input type="hidden" name="operations" value="0">
    <input type="checkbox" name="operations" id="operations" value="1" <?=checked($this->element->operations)?>>
    OSG-Operations&nbsp;&nbsp;&nbsp;

    <input type="hidden" name="sites" value="0">
    <input type="checkbox" name="sites" id="sites" value="1" <?=checked($this->element->sites)?>>
    OSG-Sites&nbsp;&nbsp;&nbsp;

    <input type="hidden" name="vulnerability" value="0">
    <input type="checkbox" name="vulnerability" id="vulnerability" value="1" <?=checked($this->element->vulnerability)?>>
    OSG-SECURITY-SOFTW-VULNERABILITY&nbsp;&nbsp;&nbsp;
</div>

<legend>Message</legend>

<?=$this->element->subject?>
<?=$this->element->body?>

<input type="hidden" name="sign" value="0">
<input type="checkbox" name="sign" id="sign" value="1" <?=checked($this->element->sign)?>>
Sign Email using GOC/DOEGrid user certificate&nbsp;&nbsp;&nbsp;

<div class="form-actions">
<button type="submit" name="submit_button" class="btn btn-primary btn-large" id="submit_button">Submit</button>
</div>

</form>

