<form action="<?=$this->escape($this->element->getAction())?>"
      method="<?=$this->escape($this->element->getMethod())?>">

<dl>
<dd>
    <h3>Send To</h3>
</dd>

<?
function checked($e)
{
    if($e->checked) return "checked=checked";
}
?>

<dd>
<label>Security Contacts</label>
<blockquote>
    <input type="checkbox" name="goc" id="goc" value="1" disabled="disabled" checked=checked/>
    GOC &nbsp;&nbsp;&nbsp;

    <input type="hidden" name="rsecurity" value="0">
    <input type="checkbox" name="rsecurity" id="rsecurity" value="1" <?=checked($this->element->rsecurity)?>>
    Resource Security Contacts&nbsp;&nbsp;&nbsp;

    <input type="hidden" name="vsecurity" value="0">
    <input type="checkbox" name="vsecurity" id="vsecurity" value="1" <?=checked($this->element->vsecurity)?>>
    VO Security Contacts&nbsp;&nbsp;&nbsp;

    <input type="hidden" name="ssecurity" value="0">
    <input type="checkbox" name="ssecurity" id="ssecurity" value="1" <?=checked($this->element->ssecurity)?>>
    SC Security Contacts&nbsp;&nbsp;&nbsp;
</blockquote>
</dd>

<dd>
    <label>Mailing Lists</label>
<blockquote>
    <input type="hidden" name="support" value="0">
    <input type="checkbox" name="support" id="support" value="1" <?=checked($this->element->support)?>>
    Support Centers&nbsp;&nbsp;&nbsp;

    <input type="hidden" name="general" value="0">
    <input type="checkbox" name="general" id="general" value="1" <?=checked($this->element->general)?>>
    OSG-General&nbsp;&nbsp;&nbsp;

    <input type="hidden" name="operations" value="0">
    <input type="checkbox" name="operations" id="operations" value="1" <?=checked($this->element->operations)?>>
    OSG-Operations&nbsp;&nbsp;&nbsp;

    <input type="hidden" name="sites" value="0">
    <input type="checkbox" name="sites" id="sites" value="1" <?=checked($this->element->sites)?>>
    OSG-Sites&nbsp;&nbsp;&nbsp;

    <input type="hidden" name="vulnerability" value="0">
    <input type="checkbox" name="vulnerability" id="vulnerability" value="1" <?=checked($this->element->vulnerability)?>>
    OSG-SECURITY-SOFTW-VULNERABILITY&nbsp;&nbsp;&nbsp;
</blockquote>
</dd>

<dd>
<h3>Message</h3>
</dd>

<?=$this->element->subject?>
<?=$this->element->body?>

<input type="hidden" name="sign" value="0">
<input type="checkbox" checked="checked" name="sign" id="sign" value="1" <?=checked($this->element->sites)?>>
Sign Email using GOC/DOEGrid user certificate&nbsp;&nbsp;&nbsp;

<?=$this->element->submit_button?>

</dl>
</form>

