<form action="<?=$this->escape($this->element->getAction())?>"
      method="<?=$this->escape($this->element->getMethod())?>">

<dl>

<?=$this->render("yourinfo.phtml", true)?>

    <h3>Issue Detail</h3>

    <?=$this->element->title?>
    <?=$this->element->down?>
    <?=$this->render("what_does_critical_mean.phtml", true)?>
    <?=$this->element->detail?>

    <?=$this->element->submit_button?>
</dl>
</form>

