<form action="<?=$this->escape($this->element->getAction())?>"
      method="<?=$this->escape($this->element->getMethod())?>">
<dl>
<dd>
    <h3>Send To</h3>
</dd>

<?
function checked($e)
{
    if($e->checked) return "checked=checked";
}
?>

<dd>
<label>Security Contacts</label>
<blockquote>
    <input type="checkbox" name="goc" id="goc" value="1" disabled="disabled" checked=checked/>
    GOC &nbsp;&nbsp;&nbsp;
    <br><br>
    
    <input type="hidden" name="rsecurity" value="0">
    <input type="checkbox" name="rsecurity" id="rsecurity" value="1" <?=checked($this->element->rsecurity)?>>
    Resource Security Contacts&nbsp;&nbsp;&nbsp;
    <p class="indent"><?php
        $address_model = new Address();
        foreach($address_model->get_resource_security() as $address) { 
            echo "<a href=\"mailto:".$address->primary_email."\">".($address->name)."</a> ";
        }
    ?></p>

    <input type="hidden" name="vsecurity" value="0">
    <input type="checkbox" name="vsecurity" id="vsecurity" value="1" <?=checked($this->element->vsecurity)?>>
    VO Security Contacts&nbsp;&nbsp;&nbsp;
    <p class="indent"><?php
        foreach($address_model->get_vo_security() as $address) { 
            echo "<a href=\"mailto:".$address->primary_email."\">".($address->name)."</a> ";
        }
    ?></p>

    <input type="hidden" name="ssecurity" value="0">
    <input type="checkbox" name="ssecurity" id="ssecurity" value="1" <?=checked($this->element->ssecurity)?>>
    SC Security Contacts&nbsp;&nbsp;&nbsp;
    <p class="indent"><?php
        foreach($address_model->get_sc_security() as $address) { 
            echo "<a href=\"mailto:".$address->primary_email."\">".($address->name)."</a> ";
        }
    ?></p>
</blockquote>
</dd>

<dd>
    <label>Mailing Lists</label>
<blockquote>
    <input type="hidden" name="support" value="0">
    <input type="checkbox" name="support" id="support" value="1" <?=checked($this->element->support)?>>
    Support Centers&nbsp;&nbsp;&nbsp;

    <input type="hidden" name="general" value="0">
    <input type="checkbox" name="general" id="general" value="1" <?=checked($this->element->general)?>>
    OSG-General&nbsp;&nbsp;&nbsp;

    <input type="hidden" name="operations" value="0">
    <input type="checkbox" name="operations" id="operations" value="1" <?=checked($this->element->operations)?>>
    OSG-Operations&nbsp;&nbsp;&nbsp;

    <input type="hidden" name="sites" value="0">
    <input type="checkbox" name="sites" id="sites" value="1" <?=checked($this->element->sites)?>>
    OSG-Sites&nbsp;&nbsp;&nbsp;
</blockquote>
</dd>

<dd>
<h3>Message</h3>
</dd>

<?=$this->element->email_from?>

<?=$this->element->subject?>
<?=$this->element->ticket?>
<?=$this->element->body?>
<?=$this->element->sig?>
<?=$this->element->rss?>
<?=$this->element->sign?>
</dl>

<dl>
<?=$this->element->submit_button?>
</dl>
</form>

