<style>
textarea {
width: 100%;
height: 200px;
}
select, input[type=text] {
width: 100%;
}
#sig {
height: 100px;
}
select.sig_loader {
width: 200px;
margin-bottom: 3px;
}
</style>
<?php
function checked($e)
{
    if($e->checked) return "checked=checked";
}
?>

<form action="<?=$this->escape($this->element->getAction())?>"
      method="<?=$this->escape($this->element->getMethod())?>" class="">

<legend>Send To</legend>

<div class="well">
    <div class="well-title">Security Contacts</div>

    <input type="checkbox" name="goc" id="goc" value="1" disabled="disabled" checked=checked/> GOC &nbsp;&nbsp;&nbsp;
    
    <input type="hidden" name="rsecurity" value="0">
    <input type="checkbox" name="rsecurity" id="rsecurity" value="1" <?=checked($this->element->rsecurity)?>> Resource Security Contacts
    <?php
        $address_model = new Address();
        $addresses = $address_model->get_resource_security();
        /*
        $content = "";
        foreach($addresses as $address) { 
            $content .= "<a href=\"mailto:".$address->primary_email."\">".($address->name)."</a> ";
        }
        */
        echo " <span class=\"label\">".count($addresses)." contacts</span>";
    ?>
    &nbsp;&nbsp;&nbsp;

    <input type="hidden" name="vsecurity" value="0">
    <input type="checkbox" name="vsecurity" id="vsecurity" value="1" <?=checked($this->element->vsecurity)?>>
    VO Security Contacts
    <?php
        $addresses = $address_model->get_vo_security();
        /*
        foreach($address_model->get_vo_security() as $address) { 
            echo "<a href=\"mailto:".$address->primary_email."\">".($address->name)."</a> ";
        }
        */
        echo " <span class=\"label\">".count($addresses)." contacts</span>";
    ?>
    &nbsp;&nbsp;&nbsp;

    <input type="hidden" name="ssecurity" value="0">
    <input type="checkbox" name="ssecurity" id="ssecurity" value="1" <?=checked($this->element->ssecurity)?>>
    SC Security Contacts
    <?php
        $addresses = $address_model->get_sc_security();
        /*
        foreach($address_model->get_sc_security() as $address) { 
            echo "<a href=\"mailto:".$address->primary_email."\">".($address->name)."</a> ";
        }
        */
        echo " <span class=\"label\">".count($addresses)." contacts</span>";
    ?>
    &nbsp;&nbsp;&nbsp;

</div><!-- well-->

<div class="well">
    <div class="well-title">Mailing Lists</div>

    <input type="hidden" name="support" value="0">
    <input type="checkbox" name="support" id="support" value="1" <?=checked($this->element->support)?>>
    Support Centers&nbsp;&nbsp;&nbsp;

    <input type="hidden" name="general" value="0">
    <input type="checkbox" name="general" id="general" value="1" <?=checked($this->element->general)?>>
    OSG-General&nbsp;&nbsp;&nbsp;

    <input type="hidden" name="operations" value="0">
    <input type="checkbox" name="operations" id="operations" value="1" <?=checked($this->element->operations)?>>
    OSG-Operations&nbsp;&nbsp;&nbsp;

    <input type="hidden" name="sites" value="0">
    <input type="checkbox" name="sites" id="sites" value="1" <?=checked($this->element->sites)?>>
    OSG-Sites&nbsp;&nbsp;&nbsp;
</div><!-- well -->

<div class="well">
    <div class="well-title">PKI</div>

    <input type="hidden" name="raa" value="0">
    <input type="checkbox" name="raa" id="raa" value="1" <?=checked($this->element->raa)?>> RA Agents
    <?php
        $addresses = $address_model->get_raa();
        echo " <span class=\"label\">".count($addresses)." contacts</span>";
    ?>
    &nbsp;&nbsp;&nbsp;

    <input type="hidden" name="rasponsor" value="0">
    <input type="checkbox" name="rasponsor" id="rasponsor" value="1" <?=checked($this->element->rasponsor)?>> RA Sponsors
    <?php
        $addresses = $address_model->get_rasponsor();
        echo " <span class=\"label\">".count($addresses)." contacts</span>";
    ?>
    &nbsp;&nbsp;&nbsp;

    <input type="hidden" name="gridadmin" value="0">
    <input type="checkbox" name="gridadmin" id="gridadmin" value="1" <?=checked($this->element->gridadmin)?>> GridAdmins
    <?php
        $addresses = $address_model->get_gridadmin();
        echo " <span class=\"label\">".count($addresses)." contacts</span>";
    ?>
    &nbsp;&nbsp;&nbsp;

    <input type="hidden" name="osgra" value="0">
    <input type="checkbox" name="osgra" id="osgra" value="1" <?=checked($this->element->osgra)?>>
    OSG-RA@opensciencegrid.org&nbsp;&nbsp;&nbsp;
</div><!-- well-->

<legend>Message</legend>

<?=$this->element->email_from?>
<?=$this->element->subject?>
<?=$this->element->ticket?>
<?=$this->element->body?>
<div class="pull-right">
    Template: <select class="sig_loader" onchange="load_sig(this);">
    <option value="goc">OSG Operations</option>
    <option value="software">OSG Software</option>
    </select>
</div>
<?=$this->element->sig?>

<input type="hidden" name="rss" value="0">
<input type="checkbox" name="rss" id="rss" value="1" <?=checked($this->element->rss)?>>
Publish to RSS
<br>



<div class="form-actions">
<button type="submit" name="submit_button" class="btn btn-primary btn-large" id="submit_button">Submit</button>
</div>

</form>

<script>
function load_sig(elem) {
    $("#sig").load("<?php echo fullbase()?>/notify/sig?type="+elem.value);
}
$(function() {
    if($("#sig").html() == "") {
        //load goc signature by default
        $("#sig").load("<?php echo fullbase()?>/notify/sig?type=goc");
    }
});
</script>
