<?include("app/views/scripts/header.phtml");?>
<style>
table.menu {
margin: 0px;
padding: 0px;
}
table.menu td {
padding-right: 20px;
}
table.menu h4 {
width: 300px;
}
</style>

<div class="bread">You are here &gt; <?=submenutitle($this->submenu_selected)?></div>
<h3>GOC Staff Tasks</h3>
<div class="bitindent">
    <table class="menu">
    <tr>
        <td>
        <h4>Communication</h4>
        <p><a href="notify">Notification Email/RSS</a></p>
        <p><a href="ra">Certificate Request Email</a></p>
        </td>

        <td>
        <h4>Admin</h4>
        <p><a href="finderror">Footprint Errors</a></p>
        <p><a href="group">Ticket Clustering</a></p>
        <p><a href="override">Assignment Override</a></p>
        </td>

        <td>
        <h4>Bulk Ticket Submitter</h4>
        <p><a href="bulkresource">Resource Tickets</a></p>
        </td>
    </tr>
    </table>
</div>

<?include("app/views/scripts/footer.phtml");?>
