<?include("app/views/scripts/header.phtml");?>
<div class="bread">You are here &gt; <?=submenutitle($this->submenu_selected)?></div>

<h3>Administration</h3>
<div class="bitindent">
    <p>You are authorized to do following as OSG GOC staff</p>
    <p><a href="finderror">Analyze Footprint related errors</a></p>
    <p><a href="group">Show Ticket Clustering</a></p>
    <p><a href="admin/ggussubmitform">Resend GGUS XML</a></p>
</div>

<?include("app/views/scripts/footer.phtml");?>
