<?include("app/views/scripts/header.phtml");?>
<style>
table.menu {
margin: 0px;
padding: 0px;
}
table.menu td {
padding-right: 20px;
}
table.menu h4 {
width: 300px;
}
</style>

<div class="bread">You are here &gt; <?=submenutitle($this->submenu_selected)?></div>
<br/>
<h3>GOC Staff Tasks</h3>
<div class="bitindent">
    <table class="menu">
    <tr>
        <td>
        <h4>Usual Notifications</h4>
         <p><a href="notify">Send Notification Email/RSS</a></p>
        </td>

        <td>
        <h4>RA Agent Related Tasks</h4>
         <p><a href="ra">Send certificate request email</a></p>
        </td>

        <td>
        <h4>GOCTicket Administrative Tasks</h4>
         <p><a href="finderror">Analyze Footprint related errors</a></p>
         <p><a href="group">Show Ticket Clustering</a></p>
        </td>
    </tr>
    </table>
    <h3>Ticket Lists</h3>
            <?foreach($this->link_teams as $team=>$links) {
                echo "<h4>";
                $team = Footprint::parse($team);
                echo "$team</h4>";
                foreach($links as $id=>$name) {
                    echo "<span><a href='mytickets?assignee=$id'>$name</a>&nbsp;&nbsp;</span>";
                }
                echo "</p>";
            }?>
    </div>

<?include("app/views/scripts/footer.phtml");?>
