<style>
input[type=text],
select,
textarea {
width: 100%;
}
textarea {
height: 200px;
}
.ccarea {
width: 48%;
}
</style>
<form action="<?=$this->escape($this->element->getAction())?>"
      method="<?=$this->escape($this->element->getMethod())?>">

<?=$this->render("yourinfo.phtml", true)?>

<legend>Issue Detail</legend>
<?=$this->element->title?>
<?=$this->element->detail?>

<label>CC</label>
<div class="ccarea">
    <?php
    $ccs = array();
    if(Zend_Registry::isRegistered("passback_ccs")) {
        $ccs = Zend_Registry::get("passback_ccs");
    }
    include_once("app/views/cc_editor.php");
    cceditor($ccs);
    ?>
</div>
<a class="btn btn-small" href="#" onclick="addcc($(this).siblings('div.ccarea'));return false;"><i class="icon-plus"></i> Add CC</a> 

<div class="form-actions">
<button type="submit" name="submit_button" class="btn btn-primary btn-large" id="submit_button">Submit</button>
</div>

</form>

