<?include("app/views/scripts/header.phtml");?>
<div class="bread">You are here &gt; <a href="<?=base()?>/<?=$this->submenu_selected?>"><?=submenutitle($this->submenu_selected)?></a> &gt; Security Announcement Ticket (This form creates a ticket which is visible only to registered OIM users)</div>
<div class="form">
<?
if($this->errors != "") {
    echo "<p class='errors'>".$this->errors."</p>";
}
?>
<?=$this->form?>
</div>
<?include("app/views/scripts/footer.phtml");?>
