<?include("app/views/scripts/header.phtml");?>

<link rel="stylesheet" type="text/css" href="<?=fullbase()?>/lib/jquery-1.3.2/plugins/datatables/css/demo_table_jui.css" />
<!--<script type="text/javascript" src="<?=fullbase()?>/lib/jquery-1.3.2/plugins/jquery.dataTables.min.js"></script>

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.16/datatables.min.css"/>
--> 
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.16/datatables.min.js"></script>

<script type="text/javascript">
$(document).ready(function() {
    $('#assigned').dataTable({
        "bJQueryUI": true,
        "bAutoWidth": false,
        "bPaginate": false,
        "bStateSave": true,
        "bInfo": false
    });
    $('#closed').dataTable({
        "bJQueryUI": true,
        "bAutoWidth": false,
        "bPaginate": false,
        "bStateSave": true,
        "bInfo": false
    });
});
</script>

<div class="bread">

<?
echo "You are here &gt; ";
echo "<a href=\"".fullbase()."/".$this->submenu_selected."\">";
echo submenutitle($this->submenu_selected)."</a> &gt; $this->page_title</div>";

echo "<h3>Assigned or CC-ed (".count($this->assigned_tickets)." Tickets)</h3>";
showtickets($this->assigned_tickets, "assigned");

echo "<h3>Closed within ".$this->closed_days." days (".count($this->closed_tickets)." Tickets)</h3>";
showtickets($this->closed_tickets, "closed");

function showtickets($tickets, $id) {
?>
    <table cellpadding="0" cellspacing="0" border="0" class="display" id="<?=$id?>">
    <thead>
        <tr>
            <th>ID</th>
            <th>Submit Date</th>
            <th>Title</th>
            <th>Update Date</th>
            <th>Next Action</th>
            <th>NAD</th>
            <th>Priority</th>
            <th>Type</th>
        </tr>
    </thead>
    <?
    foreach($tickets as $ticket) {
        $url = base()."/".$ticket->mrid;
        $target = "ticket_".$ticket->mrid;
    ?>
        <tr onclick="window.open('<?=$url?>','<?=$target?>');">
            <td><?=$ticket->mrid?></td>
            <td><?=$ticket->mrsubmitdate?></td>
            <td><?=$ticket->mrtitle?></td>
            <td><?=$ticket->mrupdatedate?></td>
            <td><?=$ticket->nextaction?></td>
            <td><?=$ticket->nad?></td>
            <td><?=Footprint::getPriority($ticket->mrpriority)?></td>
            <td><?=Footprint::parse($ticket->tickettype)?></td>
        </tr>
    <?
    }
    ?>
    </table>
<?
}
?>

<?include("app/views/scripts/footer.phtml");?>
